'use strict';

var devices = (function (my) {

////////////////////////////////////////////////////////
// VENDOR_ID
// (vendor name -> vendor ID lookup table)

my.VENDOR_ID = {
	/* TODO(jracle): find a way to bulk-fill it

	Frys : 
	Ingram : 
	ClubMac : 
	NebraskaFurnitureMart : 
	ChipsbankMicroelectronics : 
	HUMAX : 
	LTS : 
	EndPoints : 
	Thesys : 
	DataBroadcasting : 
	Atmel : 
	IwatsuAmerica : 
	Mitel : 
	Mitsumi : 
	HP : 
	Genoa : 
	Oak : 
	Adaptec : 
	Diebold : 
	SiemensEM : 
	EpsonImaging : 
	KeyTronic : 
	OPTi : 
	Elitegroup : 
	Xilinx : 
	Farallon : 
	NationalSemiconductor : 
	NationalRegistry : 
	ALi : 
	FutureTechnologyDevices : 
	NCR : 
	Synopsys : 
	FujitsuICLComputers : 
	FujitsuPersonalSystems : 
	Quanta : 
	NEC : 
	Kodak : 
	Weltrend : 
	VTechComputers : 
	VIATechnologies : 
	MCCI : 
	EchoSpeech : 
	MelCo : 
	Award : 
	Leadtek : 
	GigaByte : 
	WinbondElectronics : 
	SymbiosLogic : 
	ASTResearch : 
	SamsungInfoSystems : 
	Phoenix : 
	d_TV : 
	S3 : 
	CreativeTechnology : 
	LCSTelegraphics : 
	Chips : 
	NokiaMobilePhones : 
	ADISystems : 
	ComputerAccessTechnology : 
	StandardMicrosystems : 
	MotorolaSemiconductorHK : 
	IntegratedDeviceTechnology : 
	MotorolaElectronics : 
	AdvancedGravisComputerTech : 
	CirrusLogic : 
	EricssonAustrian : 
	IntelHex : 
	InnovativeSemiconductors : 
	Micronics : 
	Acer : 
	Molex : 
	SunMicrosystems : 
	ItacSystems : 
	Unisys : 
	AlpsElectric : 
	SamsungInfoSystemsHex : 
	Hyundai : 
	TaugagreiningHF : 
	FramatomeConnectorsUSA : 
	AdvancedMicroDevices : 
	VoiceTechnologiesGroup : 
	Lexmark : 
	LGElectronicsUSA : 
	RadiSys : 
	EizoNanao : 
	WinbondSystems : 
	Ericsson : 
	Gateway : 
	LucentInc : 
	NMB : 
	MomentumMicrosystems : 
	Shamrock : 
	WSI : 
	CclItri : 
	SiemensNixdorf : 
	AlpsElectricCo : 
	ThrustMaster : 
	DFIInc : 
	TexasInstruments : 
	MitsubishiElectronics : 
	CMD : 
	VobisMicrocomputerAG : 
	Telematics : 
	AnalogDevices : 
	SiliconIntegratedSystems : 
	KYE : 
	AdobeSystems : 
	SONICblue : 
	Hitachi : 
	NortelNetworks : 
	Microsoft : 
	AceCadEnterprise : 
	Primax : 
	MGEUPSSystems : 
	AMP_Tycoelectronics : 
	ATTParadyne : 
	Wieson : 
	Cherry : 
	AmericanMegatrends : 
	ToshibaDigitalMediaEquipment : 
	*/
	Logitech : 0x046d,
	/*
	BehaviorTechComputer : 
	CrystalSemiconductor : 
	Philips : 
	ChiconyElectronics : 
	SanyoInformationBusiness : 
	SanyoElectric : 
	Relisys_TecoInformationSystem : 
	AESP : 
	Seagate : 
	Connectix : 
	AdvancedPeripheralLaboratories : 
	Semtech : 
	Silitek : 
	DellComputer : 
	Kensington : 
	AgereSystems : 
	Plantronics : 
	ToshibaInfoSystemsAmerica : 
	ZenithDataSystems : 
	Kyocera : 
	SGSThomson : 
	Specialix : 
	NokiaMonitors : 
	ASUS : 
	StewartConnector : 
	Cirque : 
	Foxconn_HonHai : 
	S_MOSSystems : 
	AlpsElectricIreland : 
	IntegratedTechnologyExpress : 
	EiconTech : 
	UnitedMicroelectronics : 
	Capetronic : 
	SamsungSemiConductor : 
	MAG : 
	ESS : 
	MicronElectronics : 
	Smile : 
	CapetronicKaohsiung : 
	Yamaha : 
	Gandalf : 
	CurtisComputerProducts : 
	AcerAdvancedLabs : 
	VLSI : 
	CompaqComputer : 
	DigitalEquipment : 
	SystemSoft : 
	FirePowerSystems : 
	TridentMicrosystems : 
	HitachiHex : 
	AcerPeripherals : 
	NokiaDisplayProducts : 
	Visioneer : 
	MultivideoLabs : 
	Canon : 
	DaeWooTelecom : 
	ChromaticResearch : 
	MicroAudiometrics : 
	DooinElectronics : 
	WinnovLP : 
	Nikon : 
	Pan : 
	IBM : 
	CypressSemiconductor : 
	ROHMLSISystemsUSA : 
	Hint : 
	CompalElectronics : 
	SeikoEpson : 
	Rainbow : 
	ToucanSystems : 
	I_ODataDevice : 
	ToshibaElectronics : 
	TeliaResearchAB : 
	TDK : 
	USRobotics3Com : 
	MethodeAsia : 
	MaxiSwitch : 
	LockheedMartin : 
	Fujitsu : 
	ToshibaElectronicsAmerica : 
	MicroMacro : 
	Konica : 
	LiteOn : 
	FujiPhotoFilm : 
	PhilipsSemiconductors : 
	Tatung : 
	ScanLogic : 
	MysonCentury : 
	Digi : 
	ITTCanon : 
	AltecLansing : 
	VidUS : 
	LSILogic : 
	Forte : 
	MentorGraphics : 
	OkiSemiconductor : 
	Microchip : 
	HoltekSemiconductor : 
	Panasonic : 
	HypertecPty : 
	HuanHsinHoldings : 
	Sharp : 
	MindShare : 
	InterlinkElectronics : 
	Iiyama : 
	Exar : 
	Zilog : 
	ACC : 
	Promise : 
	SCMMicrosystems : 
	EloTouchSystems : 
	SamsungElectronics : 
	PC_Tel : 
	Brooktree : 
	NorthstarSystems : 
	TokyoElectronDevice : 
	Annabooks : 
	PacificElectronic : 
	DaewooElectronics : 
	VictorCompanyofJapan : 
	ChiconyElectronicsHex : 
	Elan : 
	HartingElektronik : 
	Fujitsu_ICLSystems : 
	Norand : 
	Newnex : 
	FuturePlusSystems : 
	BrotherIndustries : 
	DallasSemiconductor : 
	BiostarMicrotech : 
	Sunplus : 
	SolitonSystems : 
	PFU : 
	E_CMOS : 
	Siam : 
	FujikuraDDK : 
	Acer1 : 
	HitachiAmerica : 
	HayesMicrocomputerProducts : 
	n3Com : 
	Hosiden : 
	Clarion : 
	AztechSystems : 
	CinchConnectors : 
	CableSystem : 
	InnoMediaInc : 
	BelkinComponents : 
	Neon : 
	KC : 
	SejinElectron : 
	N_Able : 
	Hualon : 
	digitalX : 
	FCIElectronics : 
	ACTC : 
	LongwellElectronics : 
	ButterflyCommunications : 
	EzKEY : 
	StarMicronics : 
	WYSE : 
	SiliconGraphics : 
	Shuttle : 
	AmericanPowerConversion : 
	ScientificAtlanta : 
	IOSystems : 
	TaiwanSemiconductorManufacturing : 
	AirbornConnectors : 
	AdvancedConnectek : 
	ATEN : 
	SolaElectronics : 
	Netchip : 
	TemicMHSSA : 
	ALTRA : 
	ATI : 
	AladdinKnowledgeSystems : 
	CrescentHeartSoftware : 
	Tekom : 
	CanonInformationSystems : 
	AvidElectronics : 
	StandardMicrosystems1 : 
	UnicoreSoftware : 
	AmericanMicrosystems : 
	WacomTechnology : 
	Systech : 
	AlcatelMobilePhones : 
	Motorola : 
	LIHTZUElectric : 
	WelchAllyn : 
	Inventec : 
	Caldera : 
	ShyhShiunTerminals : 
	PrehWerkeKG : 
	GlobalVillageCommunication : 
	MicroelectronicMechatronic : 
	SiliconArchitect : 
	MobilityElectronics : 
	Synopsys1 : 
	UniAccessAB : 
	Sirf : 
	ViewSonic : 
	CristieElectronics : 
	Xirlink : 
	Polaroid : 
	AnchorChips : 
	TyanComputer : 
	Pixera : 
	FujitsuMicroelectronics : 
	NewMedia : 
	Sony : 
	Try : 
	Proside : 
	WYSETaiwan : 
	FujiXerox : 
	CompuTrendSystems : 
	PhilipsMonitors : 
	VLSIVision : 
	Dictaphone : 
	ANAMST : 
	AsahiKaseiMicrosystems : 
	ATENInternational : 
	Truevision : 
	CadenceDesignSystems : 
	KenwoodUSA : 
	KnowledgeTek : 
	ProtonElectronicInd : 
	SamsungElectro_Mechanics : 
	CTXOpto_Electronics : 
	MustekSystems : 
	Interface : 
	OasisDesign : 
	TelexCommunications : 
	Immersion : 
	ChinonIndustries : 
	PeracomNetworks : 
	Monterey : 
	Xyratex : 
	QuartzIngenierie : 
	SegaSoft : 
	Wacom : 
	Decicon : 
	eTEKLabs : 
	EIZO : 
	Elecom : 
	KoreaDataSystems : 
	Epson : 
	Interex : 
	ConexantSystems : 
	ZoranPersonalMediaDivision : 
	CityUniversityofHongKong : 
	PhilipsCreativeDisplaySolutions : 
	BAFO_QualityComputerAccessories : 
	Elsa : 
	Intrinsix : 
	GVC : 
	SamsungElectronicsAmerica : 
	Y_EData : 
	AVM : 
	SharkMultimediaInc : 
	Nintendo : 
	QuickShot : 
	Denron : 
	RacalDataGroup : 
	Roland : 
	Padix : 
	RATOCSystem : 
	FlashPoint : 
	ZyXELCommunications : 
	Kotobuki : 
	Sapien : 
	Victron : 
	Nohau : 
	Infineon : 
	InFocusSystems : 
	MicrelSemiconductor : 
	Tripath : 
	AlcorMicro : 
	Omron : 
	QuestraConsulting : 
	Powerware : 
	Incite : 
	PrincetonGraphicSystems : 
	ZoranMicroelectronics : 
	MicroTouchSystems : 
	TrisignalCommunications : 
	NiigataCanotec : 
	BrillianceSemiconductor : 
	SpectrumSignalProcessing : 
	Iomega : 
	A_Trend : 
	AdvancedInputDevices : 
	IntelligentInstrumentation : 
	LaCie : 
	Vetronix : 
	USC : 
	FujiFilmMicrodevices : 
	ARC : 
	Ortek : 
	SampoTechnology : 
	CiscoSystemsInc : 
	Bose : 
	SpacetecIMC : 
	OmniVision : 
	UtiluxSouthChina : 
	in_SystemDesign : 
	AppleComputer : 
	YCCableUSA : 
	Synopsys2 : 
	Jing_MoldEnterprise : 
	Fountain : 
	FirstComputer : 
	LGSemicon : 
	Dialogic : 
	Proxima : 
	MedianixSemiconductor : 
	Agiler : 
	PhilipsResearchLaboratories : 
	DigitalPersona : 
	GreyCellSystems : 
	n3GGreenGreenGlobe : 
	RAFIKG : 
	TycoElectronics : 
	SSResearch : 
	Keil : 
	KawasakiMicroelectronics : 
	MediaPhonics : 
	DigiInc : 
	Qualcomm : 
	Qtronix : 
	ChengUeiPrecisionIndustry : 
	SemtechHex : 
	Ricoh : 
	PowerVision : 
	ELSAAG : 
	Silicom : 
	sci_worx : 
	SungForn : 
	GEMedicalSystemsLunar : 
	Brainboxes : 
	WaveSystems : 
	TohokuRicoh : 
	SuperGate : 
	PhilipsSemiconductorsCICT : 
	ThomasBetts : 
	UltimaElectronics : 
	AxiohmTransactionSolutions : 
	Microtek : 
	Sun : 
	LexarMedia : 
	DeltaElectronics : 
	SiliconVision : 
	Symbol : 
	SyntekSemiconductor : 
	ElecVision : 
	GenesysLogic : 
	RedWing : 
	FujiElectric : 
	KeithleyInstruments : 
	ICC : 
	KawasakiLSI : 
	FFC : 
	COM21 : 
	Cytechinfo : 
	AVB : 
	Canopus : 
	CompassCommunications : 
	Dexin : 
	PIEngineering : 
	Unixtar : 
	AOC : 
	RFCDistribution : 
	PSCScanning : 
	SiemensTelecom : 
	HarmanMultimedia : 
	InterAct : 
	Chic : 
	LeCroy : 
	BarcoDisplaySystems : 
	JazzHipster : 
	VistaImaging : 
	Novatek : 
	Jean : 
	AnchorCC : 
	RoyalInformationElectronics : 
	BridgeInformation : 
	GenradAds : 
	SMKManufacturing : 
	WorthingtonDataSolutions : 
	SolidYear : 
	EEHDatalink : 
	Auctor : 
	Transmonde : 
	JoinsoonElectronicsMfg : 
	CostarElectronics : 
	TotokuElectric : 
	TransAct : 
	Bio_RadLaboratories : 
	QuabbinWireCable : 
	FutureTechnoDesignsPVT : 
	SwissFederalInstituteOfTechnology : 
	MacAlly : 
	SeikoInstruments : 
	VeridicomInc : 
	PromptusCommunications : 
	ActLabs : 
	Quatech : 
	NisseiElectric : 
	Alaris : 
	ODU_SteckverbindungssystemeKG : 
	Iotech : 
	Littelfuse : 
	Avocent : 
	TiMedia : 
	NipponSystemsDevelopment : 
	Adomax : 
	TaskingSoftware : 
	Zida : 
	CreativeLabs : 
	GreatlinkElectronicsTaiwan : 
	InstituteforInformationIndustry : 
	TaiHao : 
	Mainsuper : 
	SinSheng : 
	Jujo : 
	Cyrix : 
	Micron : 
	Methode : 
	SierraImaging : 
	Avision : 
	Chrontel : 
	Techwin : 
	TaugagreiningHFHex : 
	YamaichiElectronics : 
	FongKaiIndustrial : 
	RealMedia : 
	NewTechnologyCable : 
	HitexDevelopmentTools : 
	WoodsIndustries : 
	VIAMedical : 
	TEAC : 
	WhoVisionSystems : 
	Umax : 
	ActonResearch : 
	InsideOutNetworks : 
	WeliScience : 
	WhiteMountainDSP : 
	Ji_HawIndustrial : 
	TriTech : 
	Suyin : 
	WIBU_SystemsAG : 
	DynaproSystems : 
	Likom : 
	StargateSolutions : 
	CNF : 
	GraniteMicrosystems : 
	SpaceShuttleHi_Tech : 
	GloryMarkElectronic : 
	TekconElectronics : 
	SigmaDesigns : 
	Aethra : 
	Optoelectronics : 
	TracewellSystems : 
	SiliconGraphicsHex : 
	GoodWay : 
	TSAY_E : 
	HamamatsuPhotonicsKK : 
	KansaiElectric : 
	TopmaxElectronic : 
	Aiwa : 
	WordWand : 
	OcePrintingSystems : 
	Total : 
	LinksysInc : 
	Entrega : 
	AcerSemiconductor : 
	SigmaTel : 
	LabtecInc : 
	HCL : 
	KeyMouseElectronicEnterprise : 
	Draytech : 
	TelesAG : 
	AiwaHex : 
	ACard : 
	Prolific : 
	EfficientNetworks : 
	Hohner : 
	Intermec : 
	Virata : 
	RealtekCPPDiv : 
	SiemensInfoCom : 
	VictorCompanyofJapanHex : 
	ActiontecElectronics : 
	Minolta : 
	Pertech : 
	Potrans : 
	CHProducts : 
	GoldenBridgeElectech : 
	HagiwaraSys_Com : 
	LegoGroup : 
	Chuntex : 
	Tektronix : 
	AskeyComputer : 
	Thomson : 
	HughesNetworkSystems : 
	Marx : 
	AlliedData : 
	Topro : 
	SaitekPLC : 
	XiamenDoowellElectron : 
	Divio : 
	MicroStore : 
	TopazSystems : 
	Westell : 
	Sysgration : 
	FujitsuLaboratories : 
	GreatlandElectronicsTaiwan : 
	ProfessionalMultimediaTestingCentre : 
	Harting : 
	Pixela : 
	AlcatelTelecom : 
	SmoothCordConnector : 
	EDA : 
	OkiData : 
	AGFA_GevaertNV : 
	AMEOptimedia : 
	Leoco : 
	Phidgets : 
	Bizlink : 
	Hagenuk : 
	InfowaveSoftware : 
	SIIG : 
	Taxan : 
	NewerTechnology : 
	Synaptics : 
	TerayonCommunicationSystems : 
	Keyspan : 
	SpheronVRAG : 
	LapLink : 
	DaewooElectronicsHex : 
	MitsubishiElectric : 
	CiscoSystems : 
	Toshiba : 
	Aashima : 
	NCD : 
	TechnicalMarketingResearch : 
	PhoenixtecPower : 
	Paradyne : 
	FoxlinkImage : 
	HeiseiElectronics : 
	Multi_TechSystems : 
	ADS : 
	AlcatelMicroelectronics : 
	TigerJetNetwork : 
	Sirius : 
	PCExpertTech : 
	IACGeometrischeIngenieursBV : 
	TNCIndustrial : 
	OpcodeSystems : 
	Emine : 
	Wintrend : 
	Guillemot : 
	HSDSrL : 
	MotorolaSemiconductor : 
	BostonAcoustics : 
	GallantComputer : 
	SupercomalWireCableSDNBHD : 
	BvtechIndustry : 
	NKK : 
	Ariel : 
	StandardMicrosystems2 : 
	Putercom : 
	SiliconSystems : 
	OkiElectricIndustry : 
	ComossElectronic : 
	ExcelCellElectronic : 
	ConnectTech : 
	MagicControl : 
	IntervalResearch : 
	NewMotion : 
	ZNK : 
	Imation : 
	TremonEnterprises : 
	Domain : 
	Xionics : 
	EiconNetworks : 
	Ariston : 
	CentilliumCommunications : 
	Vanguard : 
	Amitm : 
	Sunix : 
	AdvancedCardSystems : 
	Susteen : 
	GoldfullElectronicsTelecommunications : 
	ViewQuest : 
	LasatCommunicationsA_S : 
	AsuscomNetwork : 
	LoromIndustrial : 
	MadCatz : 
	Suncom : 
	ChapletSystems : 
	EutronSpa : 
	NECInc : 
	SyntechInformation : 
	Onkyo : 
	Labway : 
	StrongManEnterprise : 
	EVerElectronics : 
	MingFortuneIndustry : 
	PolestarTech : 
	C_C_CGroupPLC : 
	Micronas : 
	DigitalStream : 
	AurealSemiconductor : 
	Network : 
	SophisticatedCircuits : 
	Midiman : 
	CyberPowerSystem : 
	X_Rite : 
	Jess_LinkProducts : 
	Tokheim : 
	Camtel : 
	Surecom : 
	Smart : 
	OmniKeyAG : 
	PartnerTech : 
	Denso : 
	KuanTechEnterprise : 
	JhenVeiElectronic : 
	AmTRAN : 
	LongshineElectronics : 
	Inalways : 
	ComdaEnterprise : 
	Volex : 
	FairchildSemiconductor : 
	SankyoSeikiMfg : 
	Linksys : 
	ForwardElectronics : 
	Griffin : 
	WellExcellentMost : 
	SanDisk : 
	Trackerball : 
	C3PO : 
	Vivitar : 
	NTT_ME : 
	Logitec : 
	HappControls : 
	GTCO_CalComp : 
	Brincom : 
	Pro_ImageManufacturing : 
	CopartnerWireandCableMfg : 
	AxisCommunicationsAB : 
	WhaYuIndustrial : 
	ABLElectronics : 
	RealChip : 
	Certicom : 
	GrandtechSemiconductor : 
	Optelec : 
	Sagem : 
	AlfadataComputer : 
	DigicomSpA : 
	NationalTechnicalSystems : 
	Onnto : 
	Be : 
	ADMtek : 
	CoregaKK : 
	Freecom : 
	Microtech : 
	Trust : 
	IMP : 
	MotorolaBCS : 
	Plustek : 
	OlympusOptical : 
	MegaWorld : 
	Marubun : 
	TIMEInterconnect : 
	D_Link : 
	CanonComputerSystems : 
	Webgear : 
	Veridicom : 
	CodeMercenariesHard_undSoftware : 
	DatafabSystems : 
	APGCashDrawer : 
	ShareWave : 
	PowertechIndustrial : 
	BUG : 
	AlliedTelesyn : 
	AVerMediaTechnologies : 
	Kingmax : 
	CarryComputer : 
	Elektor : 
	CasioComputer : 
	Dazzle : 
	D_LinkSystem : 
	AptioProducts : 
	Cyberdata : 
	GCC : 
	ArasanChipSystems : 
	DavidElectronics : 
	Ambient : 
	Elmeg : 
	PlanexCommunications : 
	MovadoEnterprise : 
	QPS : 
	AlliedCable : 
	MirvoToys : 
	Labsystems : 
	IwatsuElectric : 
	double_H : 
	TaiyoElectricWireCable : 
	TorexRetail : 
	CircuitAssembly : 
	Century : 
	Dotop : 
	Draytek : 
	MarkoftheUnicorn : 
	MagTek : 
	Mako : 
	ZoomTelephonics : 
	Genicom : 
	Evermuch : 
	DatalogicSpA : 
	TecoImageSystems : 
	PersonalCommunicationSystems : 
	Mattel : 
	MGLogic : 
	Indigita : 
	Mipsys : 
	AlphaSmart : 
	Reudo : 
	GCProtronics : 
	DataTransit : 
	BroadLogic : 
	Sato : 
	DirecTVBroadband : 
	Handspring : 
	Palm : 
	KouwellElectronics : 
	Sourcenext : 
	ActionStarEnterprise : 
	SamsungTechwin : 
	Accton : 
	GlobalVillage : 
	ArgosyResearch : 
	Rioportcom : 
	WellandIndustrial : 
	Net_Gear : 
	MintonOpticIndustry : 
	KBGear : 
	Empeg : 
	FastPoint : 
	Macronix : 
	CSEM : 
	ActiveWire : 
	BBElectronics : 
	HitachiMaxell : 
	MinoltaSystemsLaboratory : 
	Xircom : 
	ColorVision : 
	TeletrolSystems : 
	Filanet : 
	NetGearHex : 
	DataTranslation : 
	EmagicSoft_undHardware : 
	DeTeWe : 
	SystemTALKS : 
	MECIMEX : 
	Metricom : 
	SanDiskInc : 
	Xpeed : 
	ATecSubsystem : 
	Comtrol : 
	Adesso_Kbtek : 
	Jaton : 
	FujitsuComputerProducts : 
	VirtualIPGroup : 
	APT : 
	RIAA : 
	BocaResearch : 
	XACAutomation : 
	HannstarElectronics : 
	MassWorks : 
	DioGraphy : 
	UnitedResearch : 
	Icron : 
	NST : 
	PrimexAerospace : 
	e9 : 
	AndreaElectronics : 
	MaceGroup : 
	SorensonVision : 
	JGordonElectronicDesign : 
	RadioShackTandy : 
	TexasInstrumentsJapan : 
	CitizenWatch : 
	PreciseBiometrics : 
	Proxim : 
	KeyNiceEnterprise : 
	n2Wire : 
	NipponTelegraphandTelephone : 
	Aiptek : 
	JueHsunInd : 
	LongWellElectronicsCorp : 
	ProductivityEnhancementProducts : 
	smartBridges : 
	VirtualInk : 
	FujitsuSiemensComputers : 
	IncrementP : 
	BilliontonSystems : 
	n3QuestionMarks : 
	Spyrus : 
	Olitec : 
	Pioneer : 
	Litronic : 
	Gemplus : 
	PanWireCable : 
	IntegratedMemoryLogic : 
	ExtendedSystems : 
	EricssonBlueRidgeLabs : 
	M_SystemsFlashDiskPioneers : 
	CCSI_Hesso : 
	Corex : 
	CTIElectronics : 
	SysTec : 
	Logic3 : 
	Vernier : 
	KeenTopEnterprise : 
	Wipro : 
	Caere : 
	SocketCommunications : 
	SiconCable : 
	DigianswerA_S : 
	AuthenTec : 
	PinnacleSystems : 
	VST : 
	Faraday : 
	Audio_Technica : 
	Trumpion : 
	Neurosmith : 
	Feiya : 
	MultiportComputerVertriebs : 
	Shining : 
	FujitsuDevices : 
	AlationSystems : 
	PhilipsSpeechProcessing : 
	Voquette : 
	GlobeSpan : 
	SmartDisk : 
	TigerElectronics : 
	Garmin : 
	Echelon : 
	GoHubs : 
	Dymo_CoStar : 
	ICMedia : 
	Xerox : 
	LakeviewResearch : 
	Summus : 
	OxfordSemiconductor : 
	AmericanBiometric : 
	ToshibaInfoSystems : 
	Sena : 
	ToshibaCorp : 
	HarmonicDataSystems : 
	Crescentec : 
	Quantum : 
	NetcomSystems : 
	Lumberg : 
	PixartImaging : 
	Plextor : 
	IntrepidControlSystems : 
	InnoSync : 
	JSTMfg : 
	OlympiaTelecomVertriebs : 
	JapanStorageBattery : 
	Photobit : 
	i2Gocom : 
	HCLIndia : 
	KORG : 
	PascoScientific : 
	Kronauermusicindigital : 
	LinkupSystems : 
	CableTelevisionLaboratories : 
	Kingston : 
	RPMSystems : 
	NVidia : 
	BSquare : 
	Agilent : 
	CompuLinkResearch : 
	CologneChipAG : 
	Portsmith : 
	Medialogic : 
	K_TecElectronics : 
	Polycom : 
	Acer2 : 
	CatalystEnterprises : 
	Feitian : 
	Gretag_MacbethAG : 
	Schlumberger : 
	Datagraphix : 
	OLECommunications : 
	AdirondackWireCable : 
	Lightsurf : 
	Beckhoff : 
	Jeilin : 
	MindsAtWorkLLC : 
	KnudsenEngineering : 
	Marunix : 
	Rosun : 
	BarunElectronics : 
	Oak1 : 
	Apricorn : 
	cabProdukttechnikCoKG : 
	Vitana : 
	INDesign : 
	IntegratedIntellectualProperty : 
	KenwoodTMI : 
	GemstareBookGroup : 
	IntegratedTelecomExpress : 
	Zippy : 
	PairGain : 
	ContechResearch : 
	VCONTelecommunications : 
	Poinchips : 
	DataTransmissionNetwork : 
	LinShiungEnterprise : 
	SmartCardTechnologies : 
	Intersil : 
	TrippLite : 
	FranklinElectronicPublishers : 
	AltiusSolutions : 
	MDSTelephoneSystems : 
	Celltrix : 
	Grundig : 
	MySmartCom : 
	AuerswaldKG : 
	ArrisInteractiveLLC : 
	Nisca : 
	ActivCard : 
	ACTiSYS : 
	Memory : 
	Workbit : 
	PsionDacomHomeNetworks : 
	CityElectronics : 
	ElectronicsTestingCenter : 
	NeoMagic : 
	VreelinEngineering : 
	ComOne : 
	KRFTech : 
	A4Tech : 
	MeasurementComputing : 
	Aimex : 
	Fellowes : 
	Addonics : 
	Intellon : 
	Jo_Dan : 
	Silutia : 
	Real3D : 
	AKAIProfessionalMI : 
	Chen_Source : 
	IMNetworks : 
	Xitel : 
	AresCom : 
	RocketChips : 
	Edu_Science : 
	SoftConnex : 
	BayAssociates : 
	MtekVision : 
	Altera : 
	Gain : 
	LiquidAudio : 
	ViA : 
	OntrakControlSystemsInc : 
	CybexComputerProducts : 
	Xentec : 
	CambridgeSiliconRadio : 
	Telebyte : 
	SpacelabsMedical : 
	Scalar : 
	Trek : 
	Pentax : 
	HeidelbergerDruckmaschinenAG : 
	HuaGeng : 
	MedtronicPhysioControl : 
	CenturySemiconductor : 
	AK_Modul_BusComputer : 
	GilatSatelliteNetworks : 
	PentaMedia : 
	NTTDoCoMo : 
	VaroVision : 
	SwissonicAG : 
	BocaSystems : 
	DavicomSemiconductor : 
	HiroseElectric : 
	I_OInterconnect : 
	FujitsuMediaDevices : 
	Computex : 
	EvolutionElectronics : 
	SteinbergSoft_undHardware : 
	LittonSystems : 
	MimakiEngineering : 
	SonyElectronics : 
	JebseeElectronics : 
	PortablePeripheral : 
	ElectronicsForImaging : 
	EAsicsNV : 
	Broadcom : 
	Diatrend : 
	Zebra : 
	MPMan : 
	ClearCube : 
	MedeliElectronics : 
	Comaide : 
	Chromaate : 
	GreenHouse : 
	IntegratedCircuitSystems : 
	UPSManufacturing : 
	Benwin : 
	CoreTechnology : 
	GameTechnology : 
	SanwaDenshi : 
	NSTL : 
	OctagonSystems : 
	Rexon : 
	ChesenElectronics : 
	Syscan : 
	NextComm : 
	MauiInnovativePeripherals : 
	IdexxLabs : 
	NITGen : 
	Picturetel : 
	JapanAviationElectronicsIndustry : 
	Candy : 
	Globlink : 
	EGO : 
	CTechnologies : 
	Intersense : 
	LavaComputerMfg : 
	DevelcoElektronik : 
	FirstDigital : 
	PerceptionDigital : 
	WincorNixdorfCoKG : 
	TriGemComputer : 
	Baromtec : 
	JapanCBM : 
	VisionShapeEuropeSA : 
	iCompression : 
	RohdeSchwarzKG : 
	NECinfrontia : 
	Digitalway : 
	ArrowStrongElectronics : 
	Ellisys : 
	Stereo_Link : 
	SanyoSemiconductor : 
	Leco : 
	IC : 
	SingingElectrons : 
	Panwest : 
	ZStar : 
	MicroSolutions : 
	OpenNetworks : 
	KogaElectronics : 
	IDTech : 
	ZyDAS : 
	Intoto : 
	Intellix : 
	Remotec : 
	ServiceQualityTechnology : 
	AllionComputer : 
	Taito : 
	NeodymSystems : 
	SystemSupport : 
	NorthShoreCircuitDesignLLP : 
	SciEssence : 
	TTPCommunications : 
	Neodio : 
	Option : 
	SilverI : 
	B2C2 : 
	Hama : 
	ZaptronixLtd : 
	TatenoDennou : 
	CumminsEngine : 
	JumpZoneNetworkProducts : 
	ASUSTekComputer : 
	TodosDataSystemAB : 
	GNNetcom : 
	AVID : 
	Pcally : 
	ITechSolutions : 
	ElectronicWarfareAssoc : 
	InsydeSoftware : 
	TransDimension : 
	YokogawaElectric : 
	JapanSystemDevelopment : 
	PanElectronics : 
	LinkEvolution : 
	Ritek : 
	Kenwood : 
	VillageCenter : 
	PNY : 
	ContourDesign : 
	HitachiULSISystems : 
	Omnidirectional : 
	IPaxess : 
	Tekram : 
	OlivettiTechcenter : 
	KikusuiElectronics : 
	Hal : 
	Playcom : 
	Sportbugcom : 
	TechnoTrendAG : 
	ASCII : 
	PineLtd : 
	MusicalElectronics : 
	Dumpries : 
	ComfortKeyboard : 
	ColoradoMicroDisplay : 
	SinbonElectronics : 
	TYISystems : 
	BeijingHanwangTechnology : 
	LakeCommunications : 
	Corel : 
	GreenElectronics : 
	Nsine : 
	NECViewtechnology : 
	OrangeMicro : 
	ADLink : 
	WonderfulWireCable : 
	ExpertMagnetics : 
	CacheVision : 
	MaximIntegratedProducts : 
	NaganoJapanRadio : 
	PortalPlayer : 
	SHIN_EISangyo : 
	EmbeddedWirelessTechnology : 
	Computone : 
	RolandDG : 
	SunriseTelecom : 
	Zeevo : 
	TaikoDenki : 
	ITRANCommunications : 
	Astrodesign : 
	Rextron : 
	ElkatElectronics : 
	ExputerSystems : 
	Plus_OneIT : 
	SigmaKoki : 
	AdvancedDigitalBroadcast : 
	ASIXElectronics : 
	SewonTelecom : 
	O2Micro : 
	PlaymatesToys : 
	Audio : 
	Dipl_IngStefanKunde : 
	Softprotec : 
	Chippo : 
	USRobotics : 
	ConcordCamera : 
	Infinilink : 
	AmbitMicrosystems : 
	Ofuji : 
	HighTechComputer : 
	MurataManufacturing : 
	NetworkAlchemy : 
	JoytechComputer : 
	HitachiSemiconductor : 
	EigerMC : 
	ZAccessSystems : 
	GeneralMeters : 
	Assistive : 
	SystemConnection : 
	Knilink : 
	FuwYngElectronics : 
	SeagateRSS : 
	IPWireless : 
	Microcube : 
	JCN : 
	ExWAY : 
	X10Wireless : 
	TelmaxCommunications : 
	ECITelecom : 
	StartekEngineering : 
	PerfectTechnicEnterprise : 
	AndrewPargeter : 
	Realtek : 
	EricssonBusinessMobileNetworksBV : 
	YMedia : 
	OrangePCS : 
	KandaTsushinKogyo : 
	TOYO : 
	Elka : 
	DOMEimagingsystems : 
	DongGuanHumenWonderfulWireCableFactory : 
	LTKIndustries : 
	Way2CallCommunications : 
	Pace : 
	IntracomSA : 
	Konexx : 
	AddonicsInc : 
	SunnyGiken : 
	FujitsuSiemensComputersHex : 
	MOTODevelopmentGroup : 
	AppianGraphics : 
	HasbroGames : 
	InfiniteDataStorage : 
	Agate : 
	ComjetInformationSystem : 
	Highpoint : 
	DuraMicro : 
	Zeroplus : 
	IrisGraphics : 
	Gyration : 
	CyberboardA_S : 
	SynerTekKorea : 
	cyberPIXIE : 
	SiliconMotion : 
	MIPS : 
	HangZhouSilanElectronics : 
	TallyPrinter : 
	LernoutHauspie : 
	TaiyoYuden : 
	Sampo : 
	Metro : 
	EagletronInc : 
	EInk : 
	eDigital : 
	DerAnElectricWireCable : 
	IFR : 
	FuruiPreciseComponent : 
	Komatsu : 
	Radius : 
	Innocom : 
	Nextcell : 
	MotorolaiDEN : 
	Microdia : 
	WaveRiderCommunications : 
	ReinerSCTKartensysteme : 
	SealevelSystems : 
	ViewPLUS : 
	Glory : 
	SpectrumDigital : 
	BillionBright : 
	ImaginativeDesignOperation : 
	VidarSystems : 
	DongGuanShinkoWire : 
	TRSMfg : 
	XytronixResearchDesign : 
	ChantSincere : 
	Toko : 
	SignalitySystemEngineering : 
	EminenceEnterprise : 
	RexonElectronics : 
	ConceptTelecom : 
	MCTElektronikladen : 
	OptronicLaboratoriesInc : 
	JMTek : 
	SipixGroup : 
	Detto : 
	NuConnex : 
	Wing_SpanEnterprise : 
	NDA : 
	KyoceraWireless : 
	HondaTsushinKogyo : 
	PathwayConnectivity : 
	Wavefly : 
	CoactiveNetworks : 
	Tempo : 
	Cesscom : 
	AppliedMicrosystems : 
	Innochips : 
	HanwoolRobotics : 
	JobinYvon : 
	SemTek : 
	Zyfer : 
	Sega : 
	STTInstrument : 
	BAESystemsCanada : 
	Castles : 
	InformationSystemsLaboratories : 
	MotorolaCGISS : 
	AscomBusinessSystems : 
	Buslink : 
	FlyingPigSystems : 
	Innovonics : 
	CelestixNetworks : 
	SingatronEnterprise : 
	Opticis : 
	TrustElectronic : 
	ShanghaiDarongElectronics : 
	Palmax : 
	Pentel : 
	Keryx : 
	UnionGeniusComputer : 
	KuonYiIndustrial : 
	GivenImaging : 
	Timex : 
	Rimage : 
	emsys : 
	Sendo : 
	Intermagic : 
	KontronMedicalAG : 
	Technotools : 
	BroadMAX : 
	Amphenol : 
	SKNet : 
	Domex : 
	TerraTecElectronic : 
	BangOlufsen : 
	NewChipSrl : 
	JSDigitech : 
	HitachiShinDinCable : 
	Z_Com : 
	e_ConnElectronic : 
	ENE : 
	AtherosCommunications : 
	Fomtex : 
	Cellink : 
	Compucable : 
	ishoniNetworks : 
	Clarisys : 
	CentralSystemResearch : 
	Inviso : 
	Minolta_QMS : 
	SafaMedia : 
	telosEDVSystementwicklung : 
	ContemporaryControls : 
	AstronElectronics : 
	MKNet : 
	HybridNetworks : 
	FengShinCable : 
	ElasticNetworks : 
	MasproDenkoh : 
	HansolElectronics : 
	BMF : 
	ArrayComm : 
	OnStreambv : 
	Hi_Touch : 
	NALTEC : 
	coaXmedia : 
	HankConnectionIndustrial : 
	LeoHuiElectricWireCable : 
	AirSpeak : 
	Rearden : 
	DahKun : 
	SriCable : 
	Tangtop : 
	Fitcom : 
	MTSSystems : 
	Ascor : 
	TaYunTerminalsIndustrial : 
	FullDer : 
	KobilSystems : 
	Maxtor : 
	NF : 
	GrapeSystems : 
	TedasAG : 
	Coherent : 
	AgereSystemsNetherlandBV : 
	EADSAirbusFrance : 
	Cleware : 
	VolexAsia : 
	HMI : 
	Holon : 
	ASKA : 
	AVLAB : 
	SolomonMicrotech : 
	Belkin : 
	Myacom : 
	CSI : 
	IVL : 
	MeiluElectronics : 
	DarfonElectronics : 
	FritzGegaufAG : 
	DXG : 
	KMJP : 
	TMT : 
	Advanet : 
	SuperLinkElectronics : 
	NSI : 
	Megapower : 
	And_OrLogic : 
	TryComputer : 
	HirakawaHewtech : 
	WinmateCommunication : 
	HitsCommunications : 
	MFPKorea : 
	PowerSentry_Newpoint : 
	JapanDistributor : 
	MARXDatentechnik : 
	Wellco : 
	TaiwanLineTekElectronic : 
	PhisonElectronics : 
	AmericanComputerDigitalComponents : 
	EssentialRealityLLC : 
	HRSilvineElectronics : 
	TechnoVision : 
	ThinkOutside : 
	OzSoftware : 
	KingJim : 
	AscomTelecommunications : 
	C_MediaElectronics : 
	PromotionDisplayTechnology : 
	GlobalSun : 
	PitneyBowes : 
	Sure_FireElectrical : 
	Skanhex : 
	SantaBarbaraInstrumentGroup : 
	MarsSemiconductor : 
	Trazer : 
	RTXTelecomAS : 
	TatShingElectrical : 
	CheeChen : 
	SanwaSupply : 
	Avaya : 
	Powercom : 
	DangerResearch : 
	SuzhouPetersPreciseIndustrial : 
	LandInstruments : 
	NipponElectro_SensoryDevices : 
	PolarElectroOY : 
	IOGear : 
	softDSP : 
	CubigGroup : 
	WestoverScientific : 
	MicroStarInternational : 
	WenTeElectronics : 
	ShianHwiPlugParts : 
	TekramHex : 
	ChungFuChenYehEnterprise : 
	JiuhShiuhPrecisionIndustry : 
	QuikTechSolutions : 
	GreatNotions : 
	TamagawaSeiki : 
	AthenaSmartcardSolutions : 
	MacpowerPeripherals : 
	SDK : 
	PrecisionSquared : 
	FirstCableLine : 
	NetworkFab : 
	AccessSolutions : 
	ContekElectronics : 
	PowerQuotient : 
	MediaQ : 
	CustomEngineeringSPA : 
	CaliforniaMicroDevices : 
	Kocom : 
	Netac : 
	HighSpeedSurfing : 
	IntegratedCircuitSolution : 
	Tamarack : 
	Datelink : 
	Ubicom : 
	BDConsumerHealthcare : 
	Novasonics : 
	LifetimeMemoryProducts : 
	FullRiseElectronic : 
	SitecomEuropeBV : 
	MobileAction : 
	ToyoCommunicationEquipment : 
	GeneralTouch : 
	NipponSystemware : 
	Winbest : 
	Gesytec : 
	JMTekHex : 
	WalexElectronic : 
	Crewave : 
	CowonSystems : 
	LiouYuaneEnterprise : 
	VinChipSystems : 
	J_PhoneEast : 
	HeartMathLLC : 
	MicroComputerControl : 
	n3Pea : 
	TiePieengineering : 
	Stratitec : 
	SmartModularTechnologies : 
	Neostar : 
	Mansella : 
	Line6 : 
	Julia : 
	ShenzhenBaoHingElectricWireCableMfr : 
	RadicaGames : 
	SpeedDragonMultimedia : 
	Active : 
	UnionPowerInformationIndustrial : 
	BitlandInformation : 
	NeltronIndustrial : 
	Hawking : 
	Fossil : 
	Megawin : 
	TokyoElectronicIndustry : 
	Hsi_ChinElectronics : 
	TVSElectronics : 
	Archos : 
	On_TechIndustry : 
	Gmate : 
	ChingTaiElectricWireCable : 
	WellForceElectronic : 
	WiebeTech : 
	VTechEngineeringCanada : 
	CsGloryEnterprise : 
	eMTechnics : 
	Future : 
	ApluxCommunications : 
	Fingerworks : 
	AdvancedAnalogicTechnologies : 
	ParallelDice : 
	TAHSINGIndustries : 
	ADTEC : 
	Streamzap : 
	Tamura : 
	Ours : 
	NihonComputer : 
	MSLEnterprises : 
	CenDyne : 
	Humax2 : 
	WIS : 
	Y_SElectronic : 
	Saint : 
	EndorAG : 
	VWeb : 
	Omega : 
	LHI : 
	AbitComputer : 
	SweetrayIndustrial : 
	Axell : 
	BallracingDevelopments : 
	GTInformationSystem : 
	InnoVISIONMultimedia : 
	ThetaLink : 
	LiteOnIT : 
	TaiSolElectronics : 
	PhogenixImaging : 
	WinMaxGroup : 
	KyotoMicroComputer : 
	Wing_TechEnterprise : 
	NoriakeItron : 
	e_MDT : 
	ShimaSeikiMfg : 
	Sarotech : 
	AMISemiconductor : 
	ComTrue : 
	Sunrich : 
	DigitalStreamTechnology : 
	D_WAVScientific : 
	HitachiCable : 
	AichiMicroIntelligent : 
	I_OMagic : 
	LynnProducts : 
	DSIDatotech : 
	PointChips : 
	Yield : 
	SMTech : 
	WemTechnology : 
	OasisSemiconductor : 
	VisualFrontierEnterprise : 
	CSLWirePlug : 
	CAS : 
	Hori : 
	EnergyFull : 
	MarsEngineering : 
	Acetek : 
	Oracom : 
	OnsetComputer : 
	FunaiElectric : 
	Iwill : 
	IOI : 
	SeniorIndustries : 
	LeaderTech : 
	FlexP : 
	ViPower : 
	GenialityMaple : 
	Priva : 
	Jess : 
	Chrysalis : 
	YFCBonEagle : 
	Kokuyo : 
	Nien_Yi : 
	Airprime : 
	RDC : 
	Nital : 
	StJohn : 
	WorldWideCableOpto : 
	Microtune : 
	Freedom : 
	WingKey : 
	DongguanWhiteHorseCableFactory : 
	KawaiMusicalInstrumentsMfg : 
	AmbiCom : 
	Prairiecomm : 
	NewAge : 
	Key : 
	NTK : 
	Varian : 
	Acrox : 
	KobeSteel : 
	Dionex : 
	Vibren : 
	IntelligentSystems : 
	DFI : 
	DQ : 
	NetBotz : 
	Fluke : 
	VTechHoldings : 
	Yazaki : 
	YoungGeneration : 
	UniwillComputer : 
	Kingnet : 
	SomaNetworks : 
	CviLux : 
	CyberBank : 
	HyunWon : 
	Lucent : 
	StarconnElectronic : 
	ATL : 
	Sotec : 
	EpoxComputer : 
	LogicControls : 
	WinpointElectronic : 
	HaurtianWireCable : 
	IncloseDesign : 
	Juan_ChernIndustrial : 
	Wistron : 
	AACom : 
	SanShingElectronics : 
	BitwiseSystems : 
	MitacInternatinal : 
	PlugandJackIndustrial : 
	DelcomEngineering : 
	DataplusSupplies : 
	ResearchInMotion : 
	SonyEricssonMobileCommunicationsAB : 
	DynastreamInnovations : 
	Tulip : 
	Tenovis : 
	DirectAccess : 
	MicroPlus : 
	in_TechElectronics : 
	Greenconn : 
	DVICO : 
	UnitedComputer : 
	CRSElectronic : 
	UMCElectronics : 
	Access : 
	Xsido : 
	MJResearch : 
	CoreValley : 
	CHISHINGComputerAccessories : 
	Aopen : 
	SpeedTech : 
	RitronicsComponents : 
	Sigma : 
	LGElectronics : 
	Apacer : 
	iRiver : 
	Emuzed : 
	AVChaseway : 
	ChouChinIndustrial : 
	Netopia : 
	FukudaDenshi : 
	MobileMediaTech : 
	SDKMFibres : 
	TST : 
	Densitron : 
	SoftronicsPty : 
	XiamenHungsEnterprise : 
	SpeedyIndustrialSupplies : 
	ElitegroupEcs : 
	Labtec : 
	ShinkoShoji : 
	Hyper_Paltek : 
	Newly : 
	TimeDomain : 
	Inovys : 
	AtlanticCoastTelesys : 
	Ramos : 
	Infotronic : 
	EtomsElectronics : 
	Winic : 
	Comax : 
	C_One : 
	Nucam : 
	Ideazon : 
	Devolo : 
	iCreate : 
	ChuYuenEnterprise : 
	WinbondElectronicsHex : 
	AMCOTEC : 
	ImmanuelElectronics : 
	BMS : 
	ComplexMicroInterconnection : 
	HsinChenEnt : 
	ONSemiconductor : 
	WesternDigital : 
	GieseckeDevrient : 
	HongJiElectricWireCable : 
	DelkinDevices : 
	ValenceSemiconductor : 
	ChinShongEnterprise : 
	EasthomeIndustrial : 
	MotorolaElectronicsHex : 
	CCYU : 
	LoyalLegend : 
	CuritelCommunications : 
	SanChiehManufacturing : 
	ConectL : 
	MoneyControls : 
	GCTSemiconductor : 
	ArlecAustralia : 
	MidoriyaElectric : 
	KidzMouse : 
	Shin_Etsukaken : 
	CanonElectronics : 
	Pantech : 
	ChloridePowerProtection : 
	Grand_tek : 
	RobertBosch : 
	SurfaceOptics : 
	DATASOFTSystems : 
	eSOL : 
	Hirotech : 
	MitsubishiMaterials : 
	SKTeletech : 
	CablesToGo : 
	USI : 
	Honeywell : 
	Princeton : 
	Comodo : 
	DiBcom : 
	TM : 
	Dinging : 
	TMTTechnology : 
	SmartHome : 
	CygnalIntegratedProducts : 
	SaneiElectric : 
	Intec : 
	Eratech : 
	GBMConnector : 
	Kycon : 
	VellemanComponents : 
	HottingerBaldwinMeasurement : 
	ManBoonManufactory : 
	UniClass : 
	ActionsSemiconductor : 
	Authenex : 
	in_WinDevelopment : 
	Post_OpVideo : 
	CablePlus : 
	NadaElectronics : 
	Vast : 
	Pictos : 
	AnubisElectronics : 
	DotDotDot : 
	VirTouch : 
	EasyPassIndustrial : 
	Brightcom : 
	AnalogDevicesCanada : 
	Pandora : 
	YMELECTRIC : 
	MedionAG : 
	VSOElectric : 
	MasterHillElectricWireandCable : 
	Cellon : 
	Tenx : 
	IntegratedSystemSolution : 
	ToshibaDigitalMediaEquipmentHex : 
	ArinTech : 
	MapowerElectronics : 
	VOneMultimedia : 
	CyberScan : 
	EverGreatElectricWireandCable : 
	Sphairon : 
	TiniusOlsenTestingMachine : 
	AlphaImaging : 
	Secugen : 
	DeLormePublishing : 
	YUANHigh_TechDevelopment : 
	TelsonElectronics : 
	Bantam : 
	SalientSystems : 
	BizConn : 
	Gigastorage : 
	Silicon10 : 
	ShengyihSteelMold : 
	SantaElectronic : 
	JNC : 
	Venture : 
	DigitalDream : 
	KyoceraElco : 
	YouYang : 
	Tripace : 
	LoyaltyFounderEnterprise : 
	YankeeRobotics : 
	Technoimagia : 
	StarShine : 
	SierraWireless : 
	ZHANQI : 
	ruwidoaustria : 
	ChipconAS : 
	Technovas : 
	GlobalMediaGroup : 
	ExitoElectronics : 
	Topfield : 
	Siemens : 
	Alcatel : 
	InterBiometrics : 
	HudsonSoft : 
	Jungsoft : 
	BelkinHex : 
	AirVast : 
	Nyko : 
	Logic3_SpectraVideoplc : 
	StrobeData : 
	TwinMOS : 
	XaxeroMarineSoftwareEngineering : 
	MarvellSemiconductor : 
	Innomedia : 
	BelkinComponentsHex : 
	Huawei : 
	Tapwave : 
	AINComm : 
	TranscendInformation : 
	Roper : 
	ICSElectronics : 
	NaturalPoint : 
	KonicaMinolta : 
	Mobility : 
	DigbysBitpileDBADBit : 
	Swissbit : 
	Netgear : 
	Q_tec : 
	Alesis : 
	Linksys1 : 
	SharkMultimedia : 
	ImcNetworks : 
	KingstonInc : 
	RadioShack : 
	MicroStarInternationalHex : 
	FormosaIndustrialComputing : 
	ElsaHex : 
	Ralink : 
	AVerMedia : 
	Atheros : 
	GemlightComputer : 
	CheshireEngineering : 
	Bitwire : 
	ENEHex : 
	JMicron : 
	LG : 
	U_BloxAG : 
	ProlinkMicrosystems : 
	SunfPu : 
	SoundGraphInc : 
	LaboratoiresMXM : 
	RSA : 
	SohoWare : 
	PacificDigital : 
	HanfTek : 
	Tascam : 
	UmaxHex : 
	InsideOutNetworksHex : 
	EntregaHex : 
	StruckInnovativeSysteme : 
	ActiontecElectronicsHex : 
	PiKRON : 
	AskeyComputerHex : 
	HitachiVideoandInformationSystem : 
	VTecTest : 
	BlueView : 
	CellinkTechnology : 
	MetaGeek : 
	GreyInnovation : 
	Cornice : 
	ChipsBnk : 
	Twinhan : 
	Compro : 
	Alienware : 
	Topseed : 
	Kaba : 
	T_Logic : 
	Trillium : 
	Energizer : 
	n2nTelekomunikace : 
	NuCORE : 
	D_LinkHex : 
	Hauppauge : 
	ActionStar : 
	Creative : 
	MacAllyHex : 
	RadioShackCorp : 
	MotorolaPCS : 
	eTurboTouch : 
	TechnologyInnovationHoldings : 
	PinnacleSystemsHex : 
	ShiningTechnologies : 
	DigitAtlway : 
	SANHODigitalElectronics : 
	Tripp_Lite : 
	TwinMOSHex : 
	ElectronicsForImagingHex : 
	NHJ : 
	ToptronicIndustrial : 
	FujitsuHex : 
	Eagletron : 
	WhanamElectronics : 
	Yakumo : 
	MicroStar : 
	PowerQuotientHex : 
	DIVA : 
	InVibro : 
	WEM : 
	NationalInstruments : 
	iRiverHex : 
	DellComputerHex : 
	USBDesignbyExample : 
	USBest : 
	ShuttleHex : 
	Panram : 
	EMSProduction : 
	Grandtec : 
	Linksys2 : 
	Transmeta : 
	UC_Logic : 
	OnSpec : 
	CoreLogic : 
	PrototypeproductVendorID : 
	Freshtel : 
	JujoShanghai : 
	Intel : 
	EGOSystems : 
	MosChip : 
	KeilInc : 
	eMPIA : 

	*/
};

////////////////////////////////////////////////////////
// VENDOR_NAME
// (vendor ID -> vendor name lookup table)

my.VENDOR_NAME = {
	0x0001: 'Frys',
	0x0002: 'Ingram',
	0x0003: 'ClubMac',
	0x0004: 'NebraskaFurnitureMart',
	0x0204: 'ChipsbankMicroelectronics',
	0x02ad: 'HUMAX',
	0x0386: 'LTS',
	0x03e8: 'EndPoints',
	0x03e9: 'Thesys',
	0x03ea: 'DataBroadcasting',
	0x03eb: 'Atmel',
	0x03ec: 'IwatsuAmerica',
	0x03ed: 'Mitel',
	0x03ee: 'Mitsumi',
	0x03f0: 'HP',
	0x03f1: 'Genoa',
	0x03f2: 'Oak',
	0x03f3: 'Adaptec',
	0x03f4: 'Diebold',
	0x03f5: 'SiemensEM',
	0x03f8: 'EpsonImaging',
	0x03f9: 'KeyTronic',
	0x03fb: 'OPTi',
	0x03fc: 'Elitegroup',
	0x03fd: 'Xilinx',
	0x03fe: 'Farallon',
	0x0400: 'NationalSemiconductor',
	0x0401: 'NationalRegistry',
	0x0402: 'ALi',
	0x0403: 'FutureTechnologyDevices',
	0x0404: 'NCR',
	0x0405: 'Synopsys',
	0x0406: 'FujitsuICLComputers',
	0x0407: 'FujitsuPersonalSystems',
	0x0408: 'Quanta',
	0x0409: 'NEC',
	0x040a: 'Kodak',
	0x040b: 'Weltrend',
	0x040c: 'VTechComputers',
	0x040d: 'VIATechnologies',
	0x040e: 'MCCI',
	0x040f: 'EchoSpeech',
	0x0411: 'MelCo',
	0x0412: 'Award',
	0x0413: 'Leadtek',
	0x0414: 'GigaByte',
	0x0416: 'WinbondElectronics',
	0x0417: 'SymbiosLogic',
	0x0418: 'ASTResearch',
	0x0419: 'SamsungInfoSystems',
	0x041a: 'Phoenix',
	0x041b: 'd_TV',
	0x041d: 'S3',
	0x041e: 'CreativeTechnology',
	0x041f: 'LCSTelegraphics',
	0x0420: 'Chips',
	0x0421: 'NokiaMobilePhones',
	0x0422: 'ADISystems',
	0x0423: 'ComputerAccessTechnology',
	0x0424: 'StandardMicrosystems',
	0x0425: 'MotorolaSemiconductorHK',
	0x0426: 'IntegratedDeviceTechnology',
	0x0427: 'MotorolaElectronics',
	0x0428: 'AdvancedGravisComputerTech',
	0x0429: 'CirrusLogic',
	0x042a: 'EricssonAustrian',
	0x042b: 'IntelHex',
	0x042c: 'InnovativeSemiconductors',
	0x042d: 'Micronics',
	0x042e: 'Acer',
	0x042f: 'Molex',
	0x0430: 'SunMicrosystems',
	0x0431: 'ItacSystems',
	0x0432: 'Unisys',
	0x0433: 'AlpsElectric',
	0x0434: 'SamsungInfoSystemsHex',
	0x0435: 'Hyundai',
	0x0436: 'TaugagreiningHF',
	0x0437: 'FramatomeConnectorsUSA',
	0x0438: 'AdvancedMicroDevices',
	0x0439: 'VoiceTechnologiesGroup',
	0x043d: 'Lexmark',
	0x043e: 'LGElectronicsUSA',
	0x043f: 'RadiSys',
	0x0440: 'EizoNanao',
	0x0441: 'WinbondSystems',
	0x0442: 'Ericsson',
	0x0443: 'Gateway',
	0x0445: 'LucentInc',
	0x0446: 'NMB',
	0x0447: 'MomentumMicrosystems',
	0x044a: 'Shamrock',
	0x044b: 'WSI',
	0x044c: 'CclItri',
	0x044d: 'SiemensNixdorf',
	0x044e: 'AlpsElectricCo',
	0x044f: 'ThrustMaster',
	0x0450: 'DFIInc',
	0x0451: 'TexasInstruments',
	0x0452: 'MitsubishiElectronics',
	0x0453: 'CMD',
	0x0454: 'VobisMicrocomputerAG',
	0x0455: 'Telematics',
	0x0456: 'AnalogDevices',
	0x0457: 'SiliconIntegratedSystems',
	0x0458: 'KYE',
	0x0459: 'AdobeSystems',
	0x045a: 'SONICblue',
	0x045b: 'Hitachi',
	0x045d: 'NortelNetworks',
	0x045e: 'Microsoft',
	0x0460: 'AceCadEnterprise',
	0x0461: 'Primax',
	0x0463: 'MGEUPSSystems',
	0x0464: 'AMP_Tycoelectronics',
	0x0467: 'ATTParadyne',
	0x0468: 'Wieson',
	0x046a: 'Cherry',
	0x046b: 'AmericanMegatrends',
	0x046c: 'ToshibaDigitalMediaEquipment',
	0x046d: 'Logitech',
	0x046e: 'BehaviorTechComputer',
	0x046f: 'CrystalSemiconductor',
	0x0471: 'Philips',
	0x0472: 'ChiconyElectronics',
	0x0473: 'SanyoInformationBusiness',
	0x0474: 'SanyoElectric',
	0x0475: 'Relisys_TecoInformationSystem',
	0x0476: 'AESP',
	0x0477: 'Seagate',
	0x0478: 'Connectix',
	0x0479: 'AdvancedPeripheralLaboratories',
	0x047a: 'Semtech',
	0x047b: 'Silitek',
	0x047c: 'DellComputer',
	0x047d: 'Kensington',
	0x047e: 'AgereSystems',
	0x047f: 'Plantronics',
	0x0480: 'ToshibaInfoSystemsAmerica',
	0x0481: 'ZenithDataSystems',
	0x0482: 'Kyocera',
	0x0483: 'SGSThomson',
	0x0484: 'Specialix',
	0x0485: 'NokiaMonitors',
	0x0486: 'ASUS',
	0x0487: 'StewartConnector',
	0x0488: 'Cirque',
	0x0489: 'Foxconn_HonHai',
	0x048a: 'S_MOSSystems',
	0x048c: 'AlpsElectricIreland',
	0x048d: 'IntegratedTechnologyExpress',
	0x048f: 'EiconTech',
	0x0490: 'UnitedMicroelectronics',
	0x0491: 'Capetronic',
	0x0492: 'SamsungSemiConductor',
	0x0493: 'MAG',
	0x0495: 'ESS',
	0x0496: 'MicronElectronics',
	0x0497: 'Smile',
	0x0498: 'CapetronicKaohsiung',
	0x0499: 'Yamaha',
	0x049a: 'Gandalf',
	0x049b: 'CurtisComputerProducts',
	0x049c: 'AcerAdvancedLabs',
	0x049d: 'VLSI',
	0x049f: 'CompaqComputer',
	0x04a0: 'DigitalEquipment',
	0x04a1: 'SystemSoft',
	0x04a2: 'FirePowerSystems',
	0x04a3: 'TridentMicrosystems',
	0x04a4: 'HitachiHex',
	0x04a5: 'AcerPeripherals',
	0x04a6: 'NokiaDisplayProducts',
	0x04a7: 'Visioneer',
	0x04a8: 'MultivideoLabs',
	0x04a9: 'Canon',
	0x04aa: 'DaeWooTelecom',
	0x04ab: 'ChromaticResearch',
	0x04ac: 'MicroAudiometrics',
	0x04ad: 'DooinElectronics',
	0x04af: 'WinnovLP',
	0x04b0: 'Nikon',
	0x04b1: 'Pan',
	0x04b3: 'IBM',
	0x04b4: 'CypressSemiconductor',
	0x04b5: 'ROHMLSISystemsUSA',
	0x04b6: 'Hint',
	0x04b7: 'CompalElectronics',
	0x04b8: 'SeikoEpson',
	0x04b9: 'Rainbow',
	0x04ba: 'ToucanSystems',
	0x04bb: 'I_ODataDevice',
	0x04bd: 'ToshibaElectronics',
	0x04be: 'TeliaResearchAB',
	0x04bf: 'TDK',
	0x04c1: 'USRobotics3Com',
	0x04c2: 'MethodeAsia',
	0x04c3: 'MaxiSwitch',
	0x04c4: 'LockheedMartin',
	0x04c5: 'Fujitsu',
	0x04c6: 'ToshibaElectronicsAmerica',
	0x04c7: 'MicroMacro',
	0x04c8: 'Konica',
	0x04ca: 'LiteOn',
	0x04cb: 'FujiPhotoFilm',
	0x04cc: 'PhilipsSemiconductors',
	0x04cd: 'Tatung',
	0x04ce: 'ScanLogic',
	0x04cf: 'MysonCentury',
	0x04d0: 'Digi',
	0x04d1: 'ITTCanon',
	0x04d2: 'AltecLansing',
	0x04d3: 'VidUS',
	0x04d4: 'LSILogic',
	0x04d5: 'Forte',
	0x04d6: 'MentorGraphics',
	0x04d7: 'OkiSemiconductor',
	0x04d8: 'Microchip',
	0x04d9: 'HoltekSemiconductor',
	0x04da: 'Panasonic',
	0x04db: 'HypertecPty',
	0x04dc: 'HuanHsinHoldings',
	0x04dd: 'Sharp',
	0x04de: 'MindShare',
	0x04df: 'InterlinkElectronics',
	0x04e1: 'Iiyama',
	0x04e2: 'Exar',
	0x04e3: 'Zilog',
	0x04e4: 'ACC',
	0x04e5: 'Promise',
	0x04e6: 'SCMMicrosystems',
	0x04e7: 'EloTouchSystems',
	0x04e8: 'SamsungElectronics',
	0x04e9: 'PC_Tel',
	0x04ea: 'Brooktree',
	0x04eb: 'NorthstarSystems',
	0x04ec: 'TokyoElectronDevice',
	0x04ed: 'Annabooks',
	0x04ef: 'PacificElectronic',
	0x04f0: 'DaewooElectronics',
	0x04f1: 'VictorCompanyofJapan',
	0x04f2: 'ChiconyElectronicsHex',
	0x04f3: 'Elan',
	0x04f4: 'HartingElektronik',
	0x04f5: 'Fujitsu_ICLSystems',
	0x04f6: 'Norand',
	0x04f7: 'Newnex',
	0x04f8: 'FuturePlusSystems',
	0x04f9: 'BrotherIndustries',
	0x04fa: 'DallasSemiconductor',
	0x04fb: 'BiostarMicrotech',
	0x04fc: 'Sunplus',
	0x04fd: 'SolitonSystems',
	0x04fe: 'PFU',
	0x04ff: 'E_CMOS',
	0x0500: 'Siam',
	0x0501: 'FujikuraDDK',
	0x0502: 'Acer1',
	0x0503: 'HitachiAmerica',
	0x0504: 'HayesMicrocomputerProducts',
	0x0506: 'n3Com',
	0x0507: 'Hosiden',
	0x0508: 'Clarion',
	0x0509: 'AztechSystems',
	0x050a: 'CinchConnectors',
	0x050b: 'CableSystem',
	0x050c: 'InnoMediaInc',
	0x050d: 'BelkinComponents',
	0x050e: 'Neon',
	0x050f: 'KC',
	0x0510: 'SejinElectron',
	0x0511: 'N_Able',
	0x0512: 'Hualon',
	0x0513: 'digitalX',
	0x0514: 'FCIElectronics',
	0x0515: 'ACTC',
	0x0516: 'LongwellElectronics',
	0x0517: 'ButterflyCommunications',
	0x0518: 'EzKEY',
	0x0519: 'StarMicronics',
	0x051a: 'WYSE',
	0x051b: 'SiliconGraphics',
	0x051c: 'Shuttle',
	0x051d: 'AmericanPowerConversion',
	0x051e: 'ScientificAtlanta',
	0x051f: 'IOSystems',
	0x0520: 'TaiwanSemiconductorManufacturing',
	0x0521: 'AirbornConnectors',
	0x0522: 'AdvancedConnectek',
	0x0523: 'ATEN',
	0x0524: 'SolaElectronics',
	0x0525: 'Netchip',
	0x0526: 'TemicMHSSA',
	0x0527: 'ALTRA',
	0x0528: 'ATI',
	0x0529: 'AladdinKnowledgeSystems',
	0x052a: 'CrescentHeartSoftware',
	0x052b: 'Tekom',
	0x052c: 'CanonInformationSystems',
	0x052d: 'AvidElectronics',
	0x052e: 'StandardMicrosystems1',
	0x052f: 'UnicoreSoftware',
	0x0530: 'AmericanMicrosystems',
	0x0531: 'WacomTechnology',
	0x0532: 'Systech',
	0x0533: 'AlcatelMobilePhones',
	0x0534: 'Motorola',
	0x0535: 'LIHTZUElectric',
	0x0536: 'WelchAllyn',
	0x0537: 'Inventec',
	0x0538: 'Caldera',
	0x0539: 'ShyhShiunTerminals',
	0x053a: 'PrehWerkeKG',
	0x053b: 'GlobalVillageCommunication',
	0x053c: 'MicroelectronicMechatronic',
	0x053d: 'SiliconArchitect',
	0x053e: 'MobilityElectronics',
	0x053f: 'Synopsys1',
	0x0540: 'UniAccessAB',
	0x0541: 'Sirf',
	0x0543: 'ViewSonic',
	0x0544: 'CristieElectronics',
	0x0545: 'Xirlink',
	0x0546: 'Polaroid',
	0x0547: 'AnchorChips',
	0x0548: 'TyanComputer',
	0x0549: 'Pixera',
	0x054a: 'FujitsuMicroelectronics',
	0x054b: 'NewMedia',
	0x054c: 'Sony',
	0x054d: 'Try',
	0x054e: 'Proside',
	0x054f: 'WYSETaiwan',
	0x0550: 'FujiXerox',
	0x0551: 'CompuTrendSystems',
	0x0552: 'PhilipsMonitors',
	0x0553: 'VLSIVision',
	0x0554: 'Dictaphone',
	0x0555: 'ANAMST',
	0x0556: 'AsahiKaseiMicrosystems',
	0x0557: 'ATENInternational',
	0x0558: 'Truevision',
	0x0559: 'CadenceDesignSystems',
	0x055a: 'KenwoodUSA',
	0x055b: 'KnowledgeTek',
	0x055c: 'ProtonElectronicInd',
	0x055d: 'SamsungElectro_Mechanics',
	0x055e: 'CTXOpto_Electronics',
	0x055f: 'MustekSystems',
	0x0560: 'Interface',
	0x0561: 'OasisDesign',
	0x0562: 'TelexCommunications',
	0x0563: 'Immersion',
	0x0564: 'ChinonIndustries',
	0x0565: 'PeracomNetworks',
	0x0566: 'Monterey',
	0x0567: 'Xyratex',
	0x0568: 'QuartzIngenierie',
	0x0569: 'SegaSoft',
	0x056a: 'Wacom',
	0x056b: 'Decicon',
	0x056c: 'eTEKLabs',
	0x056d: 'EIZO',
	0x056e: 'Elecom',
	0x056f: 'KoreaDataSystems',
	0x0570: 'Epson',
	0x0571: 'Interex',
	0x0572: 'ConexantSystems',
	0x0573: 'ZoranPersonalMediaDivision',
	0x0574: 'CityUniversityofHongKong',
	0x0575: 'PhilipsCreativeDisplaySolutions',
	0x0576: 'BAFO_QualityComputerAccessories',
	0x0577: 'Elsa',
	0x0578: 'Intrinsix',
	0x0579: 'GVC',
	0x057a: 'SamsungElectronicsAmerica',
	0x057b: 'Y_EData',
	0x057c: 'AVM',
	0x057d: 'SharkMultimediaInc',
	0x057e: 'Nintendo',
	0x057f: 'QuickShot',
	0x0580: 'Denron',
	0x0581: 'RacalDataGroup',
	0x0582: 'Roland',
	0x0583: 'Padix',
	0x0584: 'RATOCSystem',
	0x0585: 'FlashPoint',
	0x0586: 'ZyXELCommunications',
	0x0587: 'Kotobuki',
	0x0588: 'Sapien',
	0x0589: 'Victron',
	0x058a: 'Nohau',
	0x058b: 'Infineon',
	0x058c: 'InFocusSystems',
	0x058d: 'MicrelSemiconductor',
	0x058e: 'Tripath',
	0x058f: 'AlcorMicro',
	0x0590: 'Omron',
	0x0591: 'QuestraConsulting',
	0x0592: 'Powerware',
	0x0593: 'Incite',
	0x0594: 'PrincetonGraphicSystems',
	0x0595: 'ZoranMicroelectronics',
	0x0596: 'MicroTouchSystems',
	0x0597: 'TrisignalCommunications',
	0x0598: 'NiigataCanotec',
	0x0599: 'BrillianceSemiconductor',
	0x059a: 'SpectrumSignalProcessing',
	0x059b: 'Iomega',
	0x059c: 'A_Trend',
	0x059d: 'AdvancedInputDevices',
	0x059e: 'IntelligentInstrumentation',
	0x059f: 'LaCie',
	0x05a0: 'Vetronix',
	0x05a1: 'USC',
	0x05a2: 'FujiFilmMicrodevices',
	0x05a3: 'ARC',
	0x05a4: 'Ortek',
	0x05a5: 'SampoTechnology',
	0x05a6: 'CiscoSystemsInc',
	0x05a7: 'Bose',
	0x05a8: 'SpacetecIMC',
	0x05a9: 'OmniVision',
	0x05aa: 'UtiluxSouthChina',
	0x05ab: 'in_SystemDesign',
	0x05ac: 'AppleComputer',
	0x05ad: 'YCCableUSA',
	0x05ae: 'Synopsys2',
	0x05af: 'Jing_MoldEnterprise',
	0x05b0: 'Fountain',
	0x05b1: 'FirstComputer',
	0x05b4: 'LGSemicon',
	0x05b5: 'Dialogic',
	0x05b6: 'Proxima',
	0x05b7: 'MedianixSemiconductor',
	0x05b8: 'Agiler',
	0x05b9: 'PhilipsResearchLaboratories',
	0x05ba: 'DigitalPersona',
	0x05bb: 'GreyCellSystems',
	0x05bc: 'n3GGreenGreenGlobe',
	0x05bd: 'RAFIKG',
	0x05be: 'TycoElectronics',
	0x05bf: 'SSResearch',
	0x05c0: 'Keil',
	0x05c1: 'KawasakiMicroelectronics',
	0x05c2: 'MediaPhonics',
	0x05c5: 'DigiInc',
	0x05c6: 'Qualcomm',
	0x05c7: 'Qtronix',
	0x05c8: 'ChengUeiPrecisionIndustry',
	0x05c9: 'SemtechHex',
	0x05ca: 'Ricoh',
	0x05cb: 'PowerVision',
	0x05cc: 'ELSAAG',
	0x05cd: 'Silicom',
	0x05ce: 'sci_worx',
	0x05cf: 'SungForn',
	0x05d0: 'GEMedicalSystemsLunar',
	0x05d1: 'Brainboxes',
	0x05d2: 'WaveSystems',
	0x05d3: 'TohokuRicoh',
	0x05d5: 'SuperGate',
	0x05d6: 'PhilipsSemiconductorsCICT',
	0x05d7: 'ThomasBetts',
	0x05d8: 'UltimaElectronics',
	0x05d9: 'AxiohmTransactionSolutions',
	0x05da: 'Microtek',
	0x05db: 'Sun',
	0x05dc: 'LexarMedia',
	0x05dd: 'DeltaElectronics',
	0x05df: 'SiliconVision',
	0x05e0: 'Symbol',
	0x05e1: 'SyntekSemiconductor',
	0x05e2: 'ElecVision',
	0x05e3: 'GenesysLogic',
	0x05e4: 'RedWing',
	0x05e5: 'FujiElectric',
	0x05e6: 'KeithleyInstruments',
	0x05e8: 'ICC',
	0x05e9: 'KawasakiLSI',
	0x05eb: 'FFC',
	0x05ec: 'COM21',
	0x05ee: 'Cytechinfo',
	0x05ef: 'AVB',
	0x05f0: 'Canopus',
	0x05f1: 'CompassCommunications',
	0x05f2: 'Dexin',
	0x05f3: 'PIEngineering',
	0x05f5: 'Unixtar',
	0x05f6: 'AOC',
	0x05f7: 'RFCDistribution',
	0x05f9: 'PSCScanning',
	0x05fa: 'SiemensTelecom',
	0x05fc: 'HarmanMultimedia',
	0x05fd: 'InterAct',
	0x05fe: 'Chic',
	0x05ff: 'LeCroy',
	0x0600: 'BarcoDisplaySystems',
	0x0601: 'JazzHipster',
	0x0602: 'VistaImaging',
	0x0603: 'Novatek',
	0x0604: 'Jean',
	0x0605: 'AnchorCC',
	0x0606: 'RoyalInformationElectronics',
	0x0607: 'BridgeInformation',
	0x0608: 'GenradAds',
	0x0609: 'SMKManufacturing',
	0x060a: 'WorthingtonDataSolutions',
	0x060b: 'SolidYear',
	0x060c: 'EEHDatalink',
	0x060d: 'Auctor',
	0x060e: 'Transmonde',
	0x060f: 'JoinsoonElectronicsMfg',
	0x0610: 'CostarElectronics',
	0x0611: 'TotokuElectric',
	0x0613: 'TransAct',
	0x0614: 'Bio_RadLaboratories',
	0x0615: 'QuabbinWireCable',
	0x0616: 'FutureTechnoDesignsPVT',
	0x0617: 'SwissFederalInstituteOfTechnology',
	0x0618: 'MacAlly',
	0x0619: 'SeikoInstruments',
	0x061a: 'VeridicomInc',
	0x061b: 'PromptusCommunications',
	0x061c: 'ActLabs',
	0x061d: 'Quatech',
	0x061e: 'NisseiElectric',
	0x0620: 'Alaris',
	0x0621: 'ODU_SteckverbindungssystemeKG',
	0x0622: 'Iotech',
	0x0623: 'Littelfuse',
	0x0624: 'Avocent',
	0x0625: 'TiMedia',
	0x0626: 'NipponSystemsDevelopment',
	0x0627: 'Adomax',
	0x0628: 'TaskingSoftware',
	0x0629: 'Zida',
	0x062a: 'CreativeLabs',
	0x062b: 'GreatlinkElectronicsTaiwan',
	0x062c: 'InstituteforInformationIndustry',
	0x062d: 'TaiHao',
	0x062e: 'Mainsuper',
	0x062f: 'SinSheng',
	0x0631: 'Jujo',
	0x0633: 'Cyrix',
	0x0634: 'Micron',
	0x0635: 'Methode',
	0x0636: 'SierraImaging',
	0x0638: 'Avision',
	0x0639: 'Chrontel',
	0x063a: 'Techwin',
	0x063b: 'TaugagreiningHFHex',
	0x063c: 'YamaichiElectronics',
	0x063d: 'FongKaiIndustrial',
	0x063e: 'RealMedia',
	0x063f: 'NewTechnologyCable',
	0x0640: 'HitexDevelopmentTools',
	0x0641: 'WoodsIndustries',
	0x0642: 'VIAMedical',
	0x0644: 'TEAC',
	0x0645: 'WhoVisionSystems',
	0x0646: 'Umax',
	0x0647: 'ActonResearch',
	0x0648: 'InsideOutNetworks',
	0x0649: 'WeliScience',
	0x064b: 'WhiteMountainDSP',
	0x064c: 'Ji_HawIndustrial',
	0x064d: 'TriTech',
	0x064e: 'Suyin',
	0x064f: 'WIBU_SystemsAG',
	0x0650: 'DynaproSystems',
	0x0651: 'Likom',
	0x0652: 'StargateSolutions',
	0x0653: 'CNF',
	0x0654: 'GraniteMicrosystems',
	0x0655: 'SpaceShuttleHi_Tech',
	0x0656: 'GloryMarkElectronic',
	0x0657: 'TekconElectronics',
	0x0658: 'SigmaDesigns',
	0x0659: 'Aethra',
	0x065a: 'Optoelectronics',
	0x065b: 'TracewellSystems',
	0x065e: 'SiliconGraphicsHex',
	0x065f: 'GoodWay',
	0x0660: 'TSAY_E',
	0x0661: 'HamamatsuPhotonicsKK',
	0x0662: 'KansaiElectric',
	0x0663: 'TopmaxElectronic',
	0x0667: 'Aiwa',
	0x0668: 'WordWand',
	0x0669: 'OcePrintingSystems',
	0x066a: 'Total',
	0x066b: 'LinksysInc',
	0x066d: 'Entrega',
	0x066e: 'AcerSemiconductor',
	0x066f: 'SigmaTel',
	0x0672: 'LabtecInc',
	0x0673: 'HCL',
	0x0674: 'KeyMouseElectronicEnterprise',
	0x0675: 'Draytech',
	0x0676: 'TelesAG',
	0x0677: 'AiwaHex',
	0x0678: 'ACard',
	0x067b: 'Prolific',
	0x067c: 'EfficientNetworks',
	0x067d: 'Hohner',
	0x067e: 'Intermec',
	0x067f: 'Virata',
	0x0680: 'RealtekCPPDiv',
	0x0681: 'SiemensInfoCom',
	0x0682: 'VictorCompanyofJapanHex',
	0x0684: 'ActiontecElectronics',
	0x0686: 'Minolta',
	0x068a: 'Pertech',
	0x068b: 'Potrans',
	0x068e: 'CHProducts',
	0x0690: 'GoldenBridgeElectech',
	0x0693: 'HagiwaraSys_Com',
	0x0694: 'LegoGroup',
	0x0698: 'Chuntex',
	0x0699: 'Tektronix',
	0x069a: 'AskeyComputer',
	0x069b: 'Thomson',
	0x069d: 'HughesNetworkSystems',
	0x069e: 'Marx',
	0x069f: 'AlliedData',
	0x06a2: 'Topro',
	0x06a3: 'SaitekPLC',
	0x06a4: 'XiamenDoowellElectron',
	0x06a5: 'Divio',
	0x06a7: 'MicroStore',
	0x06a8: 'TopazSystems',
	0x06a9: 'Westell',
	0x06aa: 'Sysgration',
	0x06ac: 'FujitsuLaboratories',
	0x06ad: 'GreatlandElectronicsTaiwan',
	0x06ae: 'ProfessionalMultimediaTestingCentre',
	0x06af: 'Harting',
	0x06b8: 'Pixela',
	0x06b9: 'AlcatelTelecom',
	0x06ba: 'SmoothCordConnector',
	0x06bb: 'EDA',
	0x06bc: 'OkiData',
	0x06bd: 'AGFA_GevaertNV',
	0x06be: 'AMEOptimedia',
	0x06bf: 'Leoco',
	0x06c2: 'Phidgets',
	0x06c4: 'Bizlink',
	0x06c5: 'Hagenuk',
	0x06c6: 'InfowaveSoftware',
	0x06c8: 'SIIG',
	0x06c9: 'Taxan',
	0x06ca: 'NewerTechnology',
	0x06cb: 'Synaptics',
	0x06cc: 'TerayonCommunicationSystems',
	0x06cd: 'Keyspan',
	0x06cf: 'SpheronVRAG',
	0x06d0: 'LapLink',
	0x06d1: 'DaewooElectronicsHex',
	0x06d3: 'MitsubishiElectric',
	0x06d4: 'CiscoSystems',
	0x06d5: 'Toshiba',
	0x06d6: 'Aashima',
	0x06d7: 'NCD',
	0x06d8: 'TechnicalMarketingResearch',
	0x06da: 'PhoenixtecPower',
	0x06db: 'Paradyne',
	0x06dc: 'FoxlinkImage',
	0x06de: 'HeiseiElectronics',
	0x06e0: 'Multi_TechSystems',
	0x06e1: 'ADS',
	0x06e4: 'AlcatelMicroelectronics',
	0x06e6: 'TigerJetNetwork',
	0x06ea: 'Sirius',
	0x06eb: 'PCExpertTech',
	0x06ef: 'IACGeometrischeIngenieursBV',
	0x06f0: 'TNCIndustrial',
	0x06f1: 'OpcodeSystems',
	0x06f2: 'Emine',
	0x06f6: 'Wintrend',
	0x06f8: 'Guillemot',
	0x06fa: 'HSDSrL',
	0x06fc: 'MotorolaSemiconductor',
	0x06fd: 'BostonAcoustics',
	0x06fe: 'GallantComputer',
	0x0701: 'SupercomalWireCableSDNBHD',
	0x0703: 'BvtechIndustry',
	0x0705: 'NKK',
	0x0706: 'Ariel',
	0x0707: 'StandardMicrosystems2',
	0x0708: 'Putercom',
	0x0709: 'SiliconSystems',
	0x070a: 'OkiElectricIndustry',
	0x070d: 'ComossElectronic',
	0x070e: 'ExcelCellElectronic',
	0x0710: 'ConnectTech',
	0x0711: 'MagicControl',
	0x0713: 'IntervalResearch',
	0x0714: 'NewMotion',
	0x0717: 'ZNK',
	0x0718: 'Imation',
	0x0719: 'TremonEnterprises',
	0x071b: 'Domain',
	0x071c: 'Xionics',
	0x071d: 'EiconNetworks',
	0x071e: 'Ariston',
	0x0723: 'CentilliumCommunications',
	0x0726: 'Vanguard',
	0x0729: 'Amitm',
	0x072e: 'Sunix',
	0x072f: 'AdvancedCardSystems',
	0x0731: 'Susteen',
	0x0732: 'GoldfullElectronicsTelecommunications',
	0x0733: 'ViewQuest',
	0x0734: 'LasatCommunicationsA_S',
	0x0735: 'AsuscomNetwork',
	0x0736: 'LoromIndustrial',
	0x0738: 'MadCatz',
	0x073b: 'Suncom',
	0x073a: 'ChapletSystems',
	0x073d: 'EutronSpa',
	0x073e: 'NECInc',
	0x0745: 'SyntechInformation',
	0x0746: 'Onkyo',
	0x0747: 'Labway',
	0x0748: 'StrongManEnterprise',
	0x0749: 'EVerElectronics',
	0x074a: 'MingFortuneIndustry',
	0x074b: 'PolestarTech',
	0x074c: 'C_C_CGroupPLC',
	0x074d: 'Micronas',
	0x074e: 'DigitalStream',
	0x0755: 'AurealSemiconductor',
	0x0757: 'Network',
	0x075b: 'SophisticatedCircuits',
	0x0763: 'Midiman',
	0x0764: 'CyberPowerSystem',
	0x0765: 'X_Rite',
	0x0766: 'Jess_LinkProducts',
	0x0767: 'Tokheim',
	0x0768: 'Camtel',
	0x0769: 'Surecom',
	0x076a: 'Smart',
	0x076b: 'OmniKeyAG',
	0x076c: 'PartnerTech',
	0x076d: 'Denso',
	0x076e: 'KuanTechEnterprise',
	0x076f: 'JhenVeiElectronic',
	0x0774: 'AmTRAN',
	0x0775: 'LongshineElectronics',
	0x0776: 'Inalways',
	0x0777: 'ComdaEnterprise',
	0x0778: 'Volex',
	0x0779: 'FairchildSemiconductor',
	0x077a: 'SankyoSeikiMfg',
	0x077b: 'Linksys',
	0x077c: 'ForwardElectronics',
	0x077d: 'Griffin',
	0x077f: 'WellExcellentMost',
	0x0781: 'SanDisk',
	0x0782: 'Trackerball',
	0x0783: 'C3PO',
	0x0784: 'Vivitar',
	0x0785: 'NTT_ME',
	0x0789: 'Logitec',
	0x078b: 'HappControls',
	0x078c: 'GTCO_CalComp',
	0x078e: 'Brincom',
	0x0790: 'Pro_ImageManufacturing',
	0x0791: 'CopartnerWireandCableMfg',
	0x0792: 'AxisCommunicationsAB',
	0x0793: 'WhaYuIndustrial',
	0x0794: 'ABLElectronics',
	0x0795: 'RealChip',
	0x0796: 'Certicom',
	0x0797: 'GrandtechSemiconductor',
	0x0798: 'Optelec',
	0x079b: 'Sagem',
	0x079d: 'AlfadataComputer',
	0x07a1: 'DigicomSpA',
	0x07a2: 'NationalTechnicalSystems',
	0x07a3: 'Onnto',
	0x07a4: 'Be',
	0x07a6: 'ADMtek',
	0x07aa: 'CoregaKK',
	0x07ab: 'Freecom',
	0x07af: 'Microtech',
	0x07b0: 'Trust',
	0x07b1: 'IMP',
	0x07b2: 'MotorolaBCS',
	0x07b3: 'Plustek',
	0x07b4: 'OlympusOptical',
	0x07b5: 'MegaWorld',
	0x07b6: 'Marubun',
	0x07b7: 'TIMEInterconnect',
	0x07b8: 'D_Link',
	0x07bc: 'CanonComputerSystems',
	0x07bd: 'Webgear',
	0x07be: 'Veridicom',
	0x07c0: 'CodeMercenariesHard_undSoftware',
	0x07c4: 'DatafabSystems',
	0x07c5: 'APGCashDrawer',
	0x07c6: 'ShareWave',
	0x07c7: 'PowertechIndustrial',
	0x07c8: 'BUG',
	0x07c9: 'AlliedTelesyn',
	0x07ca: 'AVerMediaTechnologies',
	0x07cb: 'Kingmax',
	0x07cc: 'CarryComputer',
	0x07cd: 'Elektor',
	0x07cf: 'CasioComputer',
	0x07d0: 'Dazzle',
	0x07d1: 'D_LinkSystem',
	0x07d2: 'AptioProducts',
	0x07d3: 'Cyberdata',
	0x07d7: 'GCC',
	0x07da: 'ArasanChipSystems',
	0x07df: 'DavidElectronics',
	0x07e1: 'Ambient',
	0x07e2: 'Elmeg',
	0x07e3: 'PlanexCommunications',
	0x07e4: 'MovadoEnterprise',
	0x07e5: 'QPS',
	0x07e6: 'AlliedCable',
	0x07e7: 'MirvoToys',
	0x07e8: 'Labsystems',
	0x07ea: 'IwatsuElectric',
	0x07eb: 'double_H',
	0x07ec: 'TaiyoElectricWireCable',
	0x07ee: 'TorexRetail',
	0x07f6: 'CircuitAssembly',
	0x07f7: 'Century',
	0x07f9: 'Dotop',
	0x07fa: 'Draytek',
	0x07fd: 'MarkoftheUnicorn',
	0x0801: 'MagTek',
	0x0802: 'Mako',
	0x0803: 'ZoomTelephonics',
	0x0809: 'Genicom',
	0x080a: 'Evermuch',
	0x080c: 'DatalogicSpA',
	0x080d: 'TecoImageSystems',
	0x0810: 'PersonalCommunicationSystems',
	0x0813: 'Mattel',
	0x081a: 'MGLogic',
	0x081b: 'Indigita',
	0x081c: 'Mipsys',
	0x081e: 'AlphaSmart',
	0x0822: 'Reudo',
	0x0825: 'GCProtronics',
	0x0826: 'DataTransit',
	0x0827: 'BroadLogic',
	0x0828: 'Sato',
	0x0829: 'DirecTVBroadband',
	0x082d: 'Handspring',
	0x0830: 'Palm',
	0x0832: 'KouwellElectronics',
	0x0833: 'Sourcenext',
	0x0835: 'ActionStarEnterprise',
	0x0839: 'SamsungTechwin',
	0x083a: 'Accton',
	0x083f: 'GlobalVillage',
	0x0840: 'ArgosyResearch',
	0x0841: 'Rioportcom',
	0x0844: 'WellandIndustrial',
	0x0846: 'Net_Gear',
	0x084d: 'MintonOpticIndustry',
	0x084e: 'KBGear',
	0x084f: 'Empeg',
	0x0850: 'FastPoint',
	0x0851: 'Macronix',
	0x0852: 'CSEM',
	0x0854: 'ActiveWire',
	0x0856: 'BBElectronics',
	0x0858: 'HitachiMaxell',
	0x0859: 'MinoltaSystemsLaboratory',
	0x085a: 'Xircom',
	0x085c: 'ColorVision',
	0x0862: 'TeletrolSystems',
	0x0863: 'Filanet',
	0x0864: 'NetGearHex',
	0x0867: 'DataTranslation',
	0x086a: 'EmagicSoft_undHardware',
	0x086c: 'DeTeWe',
	0x086e: 'SystemTALKS',
	0x086f: 'MECIMEX',
	0x0870: 'Metricom',
	0x0871: 'SanDiskInc',
	0x0873: 'Xpeed',
	0x0874: 'ATecSubsystem',
	0x0879: 'Comtrol',
	0x087c: 'Adesso_Kbtek',
	0x087d: 'Jaton',
	0x087e: 'FujitsuComputerProducts',
	0x087f: 'VirtualIPGroup',
	0x0880: 'APT',
	0x0883: 'RIAA',
	0x0885: 'BocaResearch',
	0x0886: 'XACAutomation',
	0x0887: 'HannstarElectronics',
	0x088b: 'MassWorks',
	0x0892: 'DioGraphy',
	0x089c: 'UnitedResearch',
	0x089d: 'Icron',
	0x089e: 'NST',
	0x089f: 'PrimexAerospace',
	0x08a5: 'e9',
	0x08a8: 'AndreaElectronics',
	0x08ae: 'MaceGroup',
	0x08b4: 'SorensonVision',
	0x08b8: 'JGordonElectronicDesign',
	0x08b9: 'RadioShackTandy',
	0x08bb: 'TexasInstrumentsJapan',
	0x08bd: 'CitizenWatch',
	0x08c3: 'PreciseBiometrics',
	0x08c4: 'Proxim',
	0x08c7: 'KeyNiceEnterprise',
	0x08c8: 'n2Wire',
	0x08c9: 'NipponTelegraphandTelephone',
	0x08ca: 'Aiptek',
	0x08cd: 'JueHsunInd',
	0x08ce: 'LongWellElectronicsCorp',
	0x08cf: 'ProductivityEnhancementProducts',
	0x08d1: 'smartBridges',
	0x08d3: 'VirtualInk',
	0x08d4: 'FujitsuSiemensComputers',
	0x08d9: 'IncrementP',
	0x08dd: 'BilliontonSystems',
	0x08de: 'n3QuestionMarks',
	0x08df: 'Spyrus',
	0x08e3: 'Olitec',
	0x08e4: 'Pioneer',
	0x08e5: 'Litronic',
	0x08e6: 'Gemplus',
	0x08e7: 'PanWireCable',
	0x08e8: 'IntegratedMemoryLogic',
	0x08e9: 'ExtendedSystems',
	0x08ea: 'EricssonBlueRidgeLabs',
	0x08ec: 'M_SystemsFlashDiskPioneers',
	0x08ee: 'CCSI_Hesso',
	0x08f0: 'Corex',
	0x08f1: 'CTIElectronics',
	0x08f5: 'SysTec',
	0x08f6: 'Logic3',
	0x08f7: 'Vernier',
	0x08f8: 'KeenTopEnterprise',
	0x08f9: 'Wipro',
	0x08fa: 'Caere',
	0x08fb: 'SocketCommunications',
	0x08fc: 'SiconCable',
	0x08fd: 'DigianswerA_S',
	0x08ff: 'AuthenTec',
	0x0900: 'PinnacleSystems',
	0x0901: 'VST',
	0x0906: 'Faraday',
	0x0909: 'Audio_Technica',
	0x090a: 'Trumpion',
	0x090b: 'Neurosmith',
	0x090c: 'Feiya',
	0x090d: 'MultiportComputerVertriebs',
	0x090e: 'Shining',
	0x090f: 'FujitsuDevices',
	0x0910: 'AlationSystems',
	0x0911: 'PhilipsSpeechProcessing',
	0x0912: 'Voquette',
	0x0915: 'GlobeSpan',
	0x0917: 'SmartDisk',
	0x0919: 'TigerElectronics',
	0x091e: 'Garmin',
	0x0920: 'Echelon',
	0x0921: 'GoHubs',
	0x0922: 'Dymo_CoStar',
	0x0923: 'ICMedia',
	0x0924: 'Xerox',
	0x0925: 'LakeviewResearch',
	0x0927: 'Summus',
	0x0928: 'OxfordSemiconductor',
	0x0929: 'AmericanBiometric',
	0x092a: 'ToshibaInfoSystems',
	0x092b: 'Sena',
	0x0930: 'ToshibaCorp',
	0x0931: 'HarmonicDataSystems',
	0x0932: 'Crescentec',
	0x0933: 'Quantum',
	0x0934: 'NetcomSystems',
	0x0939: 'Lumberg',
	0x093a: 'PixartImaging',
	0x093b: 'Plextor',
	0x093c: 'IntrepidControlSystems',
	0x093d: 'InnoSync',
	0x093e: 'JSTMfg',
	0x093f: 'OlympiaTelecomVertriebs',
	0x0940: 'JapanStorageBattery',
	0x0941: 'Photobit',
	0x0942: 'i2Gocom',
	0x0943: 'HCLIndia',
	0x0944: 'KORG',
	0x0945: 'PascoScientific',
	0x0948: 'Kronauermusicindigital',
	0x094b: 'LinkupSystems',
	0x094d: 'CableTelevisionLaboratories',
	0x0951: 'Kingston',
	0x0954: 'RPMSystems',
	0x0955: 'NVidia',
	0x0956: 'BSquare',
	0x0957: 'Agilent',
	0x0958: 'CompuLinkResearch',
	0x0959: 'CologneChipAG',
	0x095a: 'Portsmith',
	0x095b: 'Medialogic',
	0x095c: 'K_TecElectronics',
	0x095d: 'Polycom',
	0x0967: 'Acer2',
	0x0968: 'CatalystEnterprises',
	0x096e: 'Feitian',
	0x0971: 'Gretag_MacbethAG',
	0x0973: 'Schlumberger',
	0x0974: 'Datagraphix',
	0x0975: 'OLECommunications',
	0x0976: 'AdirondackWireCable',
	0x0977: 'Lightsurf',
	0x0978: 'Beckhoff',
	0x0979: 'Jeilin',
	0x097a: 'MindsAtWorkLLC',
	0x097b: 'KnudsenEngineering',
	0x097c: 'Marunix',
	0x097d: 'Rosun',
	0x097f: 'BarunElectronics',
	0x0981: 'Oak1',
	0x0984: 'Apricorn',
	0x0985: 'cabProdukttechnikCoKG',
	0x098c: 'Vitana',
	0x098d: 'INDesign',
	0x098e: 'IntegratedIntellectualProperty',
	0x098f: 'KenwoodTMI',
	0x0993: 'GemstareBookGroup',
	0x0996: 'IntegratedTelecomExpress',
	0x099a: 'Zippy',
	0x09a3: 'PairGain',
	0x09a4: 'ContechResearch',
	0x09a5: 'VCONTelecommunications',
	0x09a6: 'Poinchips',
	0x09a7: 'DataTransmissionNetwork',
	0x09a8: 'LinShiungEnterprise',
	0x09a9: 'SmartCardTechnologies',
	0x09aa: 'Intersil',
	0x09ae: 'TrippLite',
	0x09b2: 'FranklinElectronicPublishers',
	0x09b3: 'AltiusSolutions',
	0x09b4: 'MDSTelephoneSystems',
	0x09b5: 'Celltrix',
	0x09bc: 'Grundig',
	0x09be: 'MySmartCom',
	0x09bf: 'AuerswaldKG',
	0x09c1: 'ArrisInteractiveLLC',
	0x09c2: 'Nisca',
	0x09c3: 'ActivCard',
	0x09c4: 'ACTiSYS',
	0x09c5: 'Memory',
	0x09cc: 'Workbit',
	0x09cd: 'PsionDacomHomeNetworks',
	0x09ce: 'CityElectronics',
	0x09cf: 'ElectronicsTestingCenter',
	0x09d1: 'NeoMagic',
	0x09d2: 'VreelinEngineering',
	0x09d3: 'ComOne',
	0x09d9: 'KRFTech',
	0x09da: 'A4Tech',
	0x09db: 'MeasurementComputing',
	0x09dc: 'Aimex',
	0x09dd: 'Fellowes',
	0x09df: 'Addonics',
	0x09e1: 'Intellon',
	0x09e5: 'Jo_Dan',
	0x09e6: 'Silutia',
	0x09e7: 'Real3D',
	0x09e8: 'AKAIProfessionalMI',
	0x09e9: 'Chen_Source',
	0x09eb: 'IMNetworks',
	0x09ef: 'Xitel',
	0x09f5: 'AresCom',
	0x09f6: 'RocketChips',
	0x09f7: 'Edu_Science',
	0x09f8: 'SoftConnex',
	0x09f9: 'BayAssociates',
	0x09fa: 'MtekVision',
	0x09fb: 'Altera',
	0x09ff: 'Gain',
	0x0a00: 'LiquidAudio',
	0x0a01: 'ViA',
	0x0a07: 'OntrakControlSystemsInc',
	0x0a0b: 'CybexComputerProducts',
	0x0a11: 'Xentec',
	0x0a12: 'CambridgeSiliconRadio',
	0x0a13: 'Telebyte',
	0x0a14: 'SpacelabsMedical',
	0x0a15: 'Scalar',
	0x0a16: 'Trek',
	0x0a17: 'Pentax',
	0x0a18: 'HeidelbergerDruckmaschinenAG',
	0x0a19: 'HuaGeng',
	0x0a21: 'MedtronicPhysioControl',
	0x0a22: 'CenturySemiconductor',
	0x0a2c: 'AK_Modul_BusComputer',
	0x0a39: 'GilatSatelliteNetworks',
	0x0a3a: 'PentaMedia',
	0x0a3c: 'NTTDoCoMo',
	0x0a3d: 'VaroVision',
	0x0a3f: 'SwissonicAG',
	0x0a43: 'BocaSystems',
	0x0a46: 'DavicomSemiconductor',
	0x0a47: 'HiroseElectric',
	0x0a48: 'I_OInterconnect',
	0x0a4b: 'FujitsuMediaDevices',
	0x0a4c: 'Computex',
	0x0a4d: 'EvolutionElectronics',
	0x0a4e: 'SteinbergSoft_undHardware',
	0x0a4f: 'LittonSystems',
	0x0a50: 'MimakiEngineering',
	0x0a51: 'SonyElectronics',
	0x0a52: 'JebseeElectronics',
	0x0a53: 'PortablePeripheral',
	0x0a5a: 'ElectronicsForImaging',
	0x0a5b: 'EAsicsNV',
	0x0a5c: 'Broadcom',
	0x0a5d: 'Diatrend',
	0x0a5f: 'Zebra',
	0x0a62: 'MPMan',
	0x0a66: 'ClearCube',
	0x0a67: 'MedeliElectronics',
	0x0a68: 'Comaide',
	0x0a69: 'Chromaate',
	0x0a6b: 'GreenHouse',
	0x0a6c: 'IntegratedCircuitSystems',
	0x0a6d: 'UPSManufacturing',
	0x0a6e: 'Benwin',
	0x0a6f: 'CoreTechnology',
	0x0a70: 'GameTechnology',
	0x0a72: 'SanwaDenshi',
	0x0a7d: 'NSTL',
	0x0a7e: 'OctagonSystems',
	0x0a80: 'Rexon',
	0x0a81: 'ChesenElectronics',
	0x0a82: 'Syscan',
	0x0a83: 'NextComm',
	0x0a84: 'MauiInnovativePeripherals',
	0x0a85: 'IdexxLabs',
	0x0a86: 'NITGen',
	0x0a8d: 'Picturetel',
	0x0a8e: 'JapanAviationElectronicsIndustry',
	0x0a90: 'Candy',
	0x0a91: 'Globlink',
	0x0a92: 'EGO',
	0x0a93: 'CTechnologies',
	0x0a94: 'Intersense',
	0x0aa3: 'LavaComputerMfg',
	0x0aa4: 'DevelcoElektronik',
	0x0aa5: 'FirstDigital',
	0x0aa6: 'PerceptionDigital',
	0x0aa7: 'WincorNixdorfCoKG',
	0x0aa8: 'TriGemComputer',
	0x0aa9: 'Baromtec',
	0x0aaa: 'JapanCBM',
	0x0aab: 'VisionShapeEuropeSA',
	0x0aac: 'iCompression',
	0x0aad: 'RohdeSchwarzKG',
	0x0aae: 'NECinfrontia',
	0x0aaf: 'Digitalway',
	0x0ab0: 'ArrowStrongElectronics',
	0x0aba: 'Ellisys',
	0x0abe: 'Stereo_Link',
	0x0ac3: 'SanyoSemiconductor',
	0x0ac4: 'Leco',
	0x0ac5: 'IC',
	0x0ac6: 'SingingElectrons',
	0x0ac7: 'Panwest',
	0x0ac8: 'ZStar',
	0x0ac9: 'MicroSolutions',
	0x0aca: 'OpenNetworks',
	0x0acc: 'KogaElectronics',
	0x0acd: 'IDTech',
	0x0ace: 'ZyDAS',
	0x0acf: 'Intoto',
	0x0ad0: 'Intellix',
	0x0ad1: 'Remotec',
	0x0ad2: 'ServiceQualityTechnology',
	0x0ae3: 'AllionComputer',
	0x0ae4: 'Taito',
	0x0ae7: 'NeodymSystems',
	0x0ae8: 'SystemSupport',
	0x0ae9: 'NorthShoreCircuitDesignLLP',
	0x0aea: 'SciEssence',
	0x0aeb: 'TTPCommunications',
	0x0aec: 'Neodio',
	0x0af0: 'Option',
	0x0af6: 'SilverI',
	0x0af7: 'B2C2',
	0x0af9: 'Hama',
	0x0afc: 'ZaptronixLtd',
	0x0afd: 'TatenoDennou',
	0x0afe: 'CumminsEngine',
	0x0aff: 'JumpZoneNetworkProducts',
	0x0b05: 'ASUSTekComputer',
	0x0b0c: 'TodosDataSystemAB',
	0x0b0e: 'GNNetcom',
	0x0b0f: 'AVID',
	0x0b10: 'Pcally',
	0x0b11: 'ITechSolutions',
	0x0b1e: 'ElectronicWarfareAssoc',
	0x0b1f: 'InsydeSoftware',
	0x0b20: 'TransDimension',
	0x0b21: 'YokogawaElectric',
	0x0b22: 'JapanSystemDevelopment',
	0x0b23: 'PanElectronics',
	0x0b24: 'LinkEvolution',
	0x0b27: 'Ritek',
	0x0b28: 'Kenwood',
	0x0b2c: 'VillageCenter',
	0x0b30: 'PNY',
	0x0b33: 'ContourDesign',
	0x0b37: 'HitachiULSISystems',
	0x0b39: 'Omnidirectional',
	0x0b3a: 'IPaxess',
	0x0b3b: 'Tekram',
	0x0b3c: 'OlivettiTechcenter',
	0x0b3e: 'KikusuiElectronics',
	0x0b41: 'Hal',
	0x0b43: 'Playcom',
	0x0b47: 'Sportbugcom',
	0x0b48: 'TechnoTrendAG',
	0x0b49: 'ASCII',
	0x0b4b: 'PineLtd',
	0x0b4e: 'MusicalElectronics',
	0x0b50: 'Dumpries',
	0x0b51: 'ComfortKeyboard',
	0x0b52: 'ColoradoMicroDisplay',
	0x0b54: 'SinbonElectronics',
	0x0b56: 'TYISystems',
	0x0b57: 'BeijingHanwangTechnology',
	0x0b59: 'LakeCommunications',
	0x0b5a: 'Corel',
	0x0b5f: 'GreenElectronics',
	0x0b60: 'Nsine',
	0x0b61: 'NECViewtechnology',
	0x0b62: 'OrangeMicro',
	0x0b63: 'ADLink',
	0x0b64: 'WonderfulWireCable',
	0x0b65: 'ExpertMagnetics',
	0x0b69: 'CacheVision',
	0x0b6a: 'MaximIntegratedProducts',
	0x0b6f: 'NaganoJapanRadio',
	0x0b70: 'PortalPlayer',
	0x0b71: 'SHIN_EISangyo',
	0x0b72: 'EmbeddedWirelessTechnology',
	0x0b73: 'Computone',
	0x0b75: 'RolandDG',
	0x0b79: 'SunriseTelecom',
	0x0b7a: 'Zeevo',
	0x0b7b: 'TaikoDenki',
	0x0b7c: 'ITRANCommunications',
	0x0b7d: 'Astrodesign',
	0x0b84: 'Rextron',
	0x0b85: 'ElkatElectronics',
	0x0b86: 'ExputerSystems',
	0x0b87: 'Plus_OneIT',
	0x0b88: 'SigmaKoki',
	0x0b89: 'AdvancedDigitalBroadcast',
	0x0b95: 'ASIXElectronics',
	0x0b96: 'SewonTelecom',
	0x0b97: 'O2Micro',
	0x0b98: 'PlaymatesToys',
	0x0b99: 'Audio',
	0x0b9b: 'Dipl_IngStefanKunde',
	0x0b9d: 'Softprotec',
	0x0b9f: 'Chippo',
	0x0baf: 'USRobotics',
	0x0bb0: 'ConcordCamera',
	0x0bb1: 'Infinilink',
	0x0bb2: 'AmbitMicrosystems',
	0x0bb3: 'Ofuji',
	0x0bb4: 'HighTechComputer',
	0x0bb5: 'MurataManufacturing',
	0x0bb6: 'NetworkAlchemy',
	0x0bb7: 'JoytechComputer',
	0x0bb8: 'HitachiSemiconductor',
	0x0bb9: 'EigerMC',
	0x0bba: 'ZAccessSystems',
	0x0bbb: 'GeneralMeters',
	0x0bbc: 'Assistive',
	0x0bbd: 'SystemConnection',
	0x0bc0: 'Knilink',
	0x0bc1: 'FuwYngElectronics',
	0x0bc2: 'SeagateRSS',
	0x0bc3: 'IPWireless',
	0x0bc4: 'Microcube',
	0x0bc5: 'JCN',
	0x0bc6: 'ExWAY',
	0x0bc7: 'X10Wireless',
	0x0bc8: 'TelmaxCommunications',
	0x0bc9: 'ECITelecom',
	0x0bca: 'StartekEngineering',
	0x0bcb: 'PerfectTechnicEnterprise',
	0x0bd7: 'AndrewPargeter',
	0x0bda: 'Realtek',
	0x0bdb: 'EricssonBusinessMobileNetworksBV',
	0x0bdc: 'YMedia',
	0x0bdd: 'OrangePCS',
	0x0be2: 'KandaTsushinKogyo',
	0x0be3: 'TOYO',
	0x0be4: 'Elka',
	0x0be5: 'DOMEimagingsystems',
	0x0be6: 'DongGuanHumenWonderfulWireCableFactory',
	0x0bee: 'LTKIndustries',
	0x0bef: 'Way2CallCommunications',
	0x0bf0: 'Pace',
	0x0bf1: 'IntracomSA',
	0x0bf2: 'Konexx',
	0x0bf6: 'AddonicsInc',
	0x0bf7: 'SunnyGiken',
	0x0bf8: 'FujitsuSiemensComputersHex',
	0x0c04: 'MOTODevelopmentGroup',
	0x0c05: 'AppianGraphics',
	0x0c06: 'HasbroGames',
	0x0c07: 'InfiniteDataStorage',
	0x0c08: 'Agate',
	0x0c09: 'ComjetInformationSystem',
	0x0c0a: 'Highpoint',
	0x0c0b: 'DuraMicro',
	0x0c12: 'Zeroplus',
	0x0c15: 'IrisGraphics',
	0x0c16: 'Gyration',
	0x0c17: 'CyberboardA_S',
	0x0c18: 'SynerTekKorea',
	0x0c19: 'cyberPIXIE',
	0x0c1a: 'SiliconMotion',
	0x0c1b: 'MIPS',
	0x0c1c: 'HangZhouSilanElectronics',
	0x0c22: 'TallyPrinter',
	0x0c23: 'LernoutHauspie',
	0x0c24: 'TaiyoYuden',
	0x0c25: 'Sampo',
	0x0c2e: 'Metro',
	0x0c35: 'EagletronInc',
	0x0c36: 'EInk',
	0x0c37: 'eDigital',
	0x0c38: 'DerAnElectricWireCable',
	0x0c39: 'IFR',
	0x0c3a: 'FuruiPreciseComponent',
	0x0c3b: 'Komatsu',
	0x0c3c: 'Radius',
	0x0c3d: 'Innocom',
	0x0c3e: 'Nextcell',
	0x0c44: 'MotorolaiDEN',
	0x0c45: 'Microdia',
	0x0c46: 'WaveRiderCommunications',
	0x0c4b: 'ReinerSCTKartensysteme',
	0x0c52: 'SealevelSystems',
	0x0c53: 'ViewPLUS',
	0x0c54: 'Glory',
	0x0c55: 'SpectrumDigital',
	0x0c56: 'BillionBright',
	0x0c57: 'ImaginativeDesignOperation',
	0x0c58: 'VidarSystems',
	0x0c59: 'DongGuanShinkoWire',
	0x0c5a: 'TRSMfg',
	0x0c5e: 'XytronixResearchDesign',
	0x0c62: 'ChantSincere',
	0x0c63: 'Toko',
	0x0c64: 'SignalitySystemEngineering',
	0x0c65: 'EminenceEnterprise',
	0x0c66: 'RexonElectronics',
	0x0c67: 'ConceptTelecom',
	0x0c70: 'MCTElektronikladen',
	0x0c74: 'OptronicLaboratoriesInc',
	0x0c76: 'JMTek',
	0x0c77: 'SipixGroup',
	0x0c78: 'Detto',
	0x0c79: 'NuConnex',
	0x0c7a: 'Wing_SpanEnterprise',
	0x0c86: 'NDA',
	0x0c88: 'KyoceraWireless',
	0x0c89: 'HondaTsushinKogyo',
	0x0c8a: 'PathwayConnectivity',
	0x0c8b: 'Wavefly',
	0x0c8c: 'CoactiveNetworks',
	0x0c8d: 'Tempo',
	0x0c8e: 'Cesscom',
	0x0c8f: 'AppliedMicrosystems',
	0x0c99: 'Innochips',
	0x0c9a: 'HanwoolRobotics',
	0x0c9b: 'JobinYvon',
	0x0c9d: 'SemTek',
	0x0ca2: 'Zyfer',
	0x0ca3: 'Sega',
	0x0ca4: 'STTInstrument',
	0x0ca5: 'BAESystemsCanada',
	0x0ca6: 'Castles',
	0x0ca7: 'InformationSystemsLaboratories',
	0x0cad: 'MotorolaCGISS',
	0x0cae: 'AscomBusinessSystems',
	0x0caf: 'Buslink',
	0x0cb0: 'FlyingPigSystems',
	0x0cb1: 'Innovonics',
	0x0cb6: 'CelestixNetworks',
	0x0cb7: 'SingatronEnterprise',
	0x0cb8: 'Opticis',
	0x0cba: 'TrustElectronic',
	0x0cbb: 'ShanghaiDarongElectronics',
	0x0cbc: 'Palmax',
	0x0cbd: 'Pentel',
	0x0cbe: 'Keryx',
	0x0cbf: 'UnionGeniusComputer',
	0x0cc0: 'KuonYiIndustrial',
	0x0cc1: 'GivenImaging',
	0x0cc2: 'Timex',
	0x0cc3: 'Rimage',
	0x0cc4: 'emsys',
	0x0cc5: 'Sendo',
	0x0cc6: 'Intermagic',
	0x0cc7: 'KontronMedicalAG',
	0x0cc8: 'Technotools',
	0x0cc9: 'BroadMAX',
	0x0cca: 'Amphenol',
	0x0ccb: 'SKNet',
	0x0ccc: 'Domex',
	0x0ccd: 'TerraTecElectronic',
	0x0cd4: 'BangOlufsen',
	0x0cd7: 'NewChipSrl',
	0x0cd8: 'JSDigitech',
	0x0cd9: 'HitachiShinDinCable',
	0x0cde: 'Z_Com',
	0x0cf1: 'e_ConnElectronic',
	0x0cf2: 'ENE',
	0x0cf3: 'AtherosCommunications',
	0x0cf4: 'Fomtex',
	0x0cf5: 'Cellink',
	0x0cf6: 'Compucable',
	0x0cf7: 'ishoniNetworks',
	0x0cf8: 'Clarisys',
	0x0cf9: 'CentralSystemResearch',
	0x0cfa: 'Inviso',
	0x0cfc: 'Minolta_QMS',
	0x0cff: 'SafaMedia',
	0x0d06: 'telosEDVSystementwicklung',
	0x0d0b: 'ContemporaryControls',
	0x0d0c: 'AstronElectronics',
	0x0d0d: 'MKNet',
	0x0d0e: 'HybridNetworks',
	0x0d0f: 'FengShinCable',
	0x0d10: 'ElasticNetworks',
	0x0d11: 'MasproDenkoh',
	0x0d12: 'HansolElectronics',
	0x0d13: 'BMF',
	0x0d14: 'ArrayComm',
	0x0d15: 'OnStreambv',
	0x0d16: 'Hi_Touch',
	0x0d17: 'NALTEC',
	0x0d18: 'coaXmedia',
	0x0d19: 'HankConnectionIndustrial',
	0x0d32: 'LeoHuiElectricWireCable',
	0x0d33: 'AirSpeak',
	0x0d34: 'Rearden',
	0x0d35: 'DahKun',
	0x0d3c: 'SriCable',
	0x0d3d: 'Tangtop',
	0x0d3e: 'Fitcom',
	0x0d3f: 'MTSSystems',
	0x0d40: 'Ascor',
	0x0d41: 'TaYunTerminalsIndustrial',
	0x0d42: 'FullDer',
	0x0d46: 'KobilSystems',
	0x0d49: 'Maxtor',
	0x0d4a: 'NF',
	0x0d4b: 'GrapeSystems',
	0x0d4c: 'TedasAG',
	0x0d4d: 'Coherent',
	0x0d4e: 'AgereSystemsNetherlandBV',
	0x0d4f: 'EADSAirbusFrance',
	0x0d50: 'Cleware',
	0x0d51: 'VolexAsia',
	0x0d53: 'HMI',
	0x0d54: 'Holon',
	0x0d55: 'ASKA',
	0x0d56: 'AVLAB',
	0x0d57: 'SolomonMicrotech',
	0x0d5c: 'Belkin',
	0x0d5e: 'Myacom',
	0x0d5f: 'CSI',
	0x0d60: 'IVL',
	0x0d61: 'MeiluElectronics',
	0x0d62: 'DarfonElectronics',
	0x0d63: 'FritzGegaufAG',
	0x0d64: 'DXG',
	0x0d65: 'KMJP',
	0x0d66: 'TMT',
	0x0d67: 'Advanet',
	0x0d68: 'SuperLinkElectronics',
	0x0d69: 'NSI',
	0x0d6a: 'Megapower',
	0x0d6b: 'And_OrLogic',
	0x0d70: 'TryComputer',
	0x0d71: 'HirakawaHewtech',
	0x0d72: 'WinmateCommunication',
	0x0d73: 'HitsCommunications',
	0x0d76: 'MFPKorea',
	0x0d77: 'PowerSentry_Newpoint',
	0x0d78: 'JapanDistributor',
	0x0d7a: 'MARXDatentechnik',
	0x0d7b: 'Wellco',
	0x0d7c: 'TaiwanLineTekElectronic',
	0x0d7d: 'PhisonElectronics',
	0x0d7e: 'AmericanComputerDigitalComponents',
	0x0d7f: 'EssentialRealityLLC',
	0x0d80: 'HRSilvineElectronics',
	0x0d81: 'TechnoVision',
	0x0d83: 'ThinkOutside',
	0x0d89: 'OzSoftware',
	0x0d8a: 'KingJim',
	0x0d8b: 'AscomTelecommunications',
	0x0d8c: 'C_MediaElectronics',
	0x0d8d: 'PromotionDisplayTechnology',
	0x0d8e: 'GlobalSun',
	0x0d8f: 'PitneyBowes',
	0x0d90: 'Sure_FireElectrical',
	0x0d96: 'Skanhex',
	0x0d97: 'SantaBarbaraInstrumentGroup',
	0x0d98: 'MarsSemiconductor',
	0x0d99: 'Trazer',
	0x0d9a: 'RTXTelecomAS',
	0x0d9b: 'TatShingElectrical',
	0x0d9c: 'CheeChen',
	0x0d9d: 'SanwaSupply',
	0x0d9e: 'Avaya',
	0x0d9f: 'Powercom',
	0x0da0: 'DangerResearch',
	0x0da1: 'SuzhouPetersPreciseIndustrial',
	0x0da2: 'LandInstruments',
	0x0da3: 'NipponElectro_SensoryDevices',
	0x0da4: 'PolarElectroOY',
	0x0da7: 'IOGear',
	0x0da8: 'softDSP',
	0x0dab: 'CubigGroup',
	0x0dad: 'WestoverScientific',
	0x0db0: 'MicroStarInternational',
	0x0db1: 'WenTeElectronics',
	0x0db2: 'ShianHwiPlugParts',
	0x0db3: 'TekramHex',
	0x0db4: 'ChungFuChenYehEnterprise',
	0x0dbe: 'JiuhShiuhPrecisionIndustry',
	0x0dbf: 'QuikTechSolutions',
	0x0dc0: 'GreatNotions',
	0x0dc1: 'TamagawaSeiki',
	0x0dc3: 'AthenaSmartcardSolutions',
	0x0dc4: 'MacpowerPeripherals',
	0x0dc5: 'SDK',
	0x0dc6: 'PrecisionSquared',
	0x0dc7: 'FirstCableLine',
	0x0dcd: 'NetworkFab',
	0x0dd0: 'AccessSolutions',
	0x0dd1: 'ContekElectronics',
	0x0dd2: 'PowerQuotient',
	0x0dd3: 'MediaQ',
	0x0dd4: 'CustomEngineeringSPA',
	0x0dd5: 'CaliforniaMicroDevices',
	0x0dd7: 'Kocom',
	0x0dd8: 'Netac',
	0x0dd9: 'HighSpeedSurfing',
	0x0dda: 'IntegratedCircuitSolution',
	0x0ddb: 'Tamarack',
	0x0ddd: 'Datelink',
	0x0dde: 'Ubicom',
	0x0de0: 'BDConsumerHealthcare',
	0x0ded: 'Novasonics',
	0x0dee: 'LifetimeMemoryProducts',
	0x0def: 'FullRiseElectronic',
	0x0df6: 'SitecomEuropeBV',
	0x0df7: 'MobileAction',
	0x0dfa: 'ToyoCommunicationEquipment',
	0x0dfc: 'GeneralTouch',
	0x0e03: 'NipponSystemware',
	0x0e08: 'Winbest',
	0x0e0c: 'Gesytec',
	0x0e16: 'JMTekHex',
	0x0e17: 'WalexElectronic',
	0x0e1b: 'Crewave',
	0x0e21: 'CowonSystems',
	0x0e23: 'LiouYuaneEnterprise',
	0x0e25: 'VinChipSystems',
	0x0e26: 'J_PhoneEast',
	0x0e30: 'HeartMathLLC',
	0x0e34: 'MicroComputerControl',
	0x0e35: 'n3Pea',
	0x0e36: 'TiePieengineering',
	0x0e38: 'Stratitec',
	0x0e39: 'SmartModularTechnologies',
	0x0e3a: 'Neostar',
	0x0e3b: 'Mansella',
	0x0e41: 'Line6',
	0x0e48: 'Julia',
	0x0e4a: 'ShenzhenBaoHingElectricWireCableMfr',
	0x0e4c: 'RadicaGames',
	0x0e55: 'SpeedDragonMultimedia',
	0x0e5a: 'Active',
	0x0e5b: 'UnionPowerInformationIndustrial',
	0x0e5c: 'BitlandInformation',
	0x0e5d: 'NeltronIndustrial',
	0x0e66: 'Hawking',
	0x0e67: 'Fossil',
	0x0e6a: 'Megawin',
	0x0e70: 'TokyoElectronicIndustry',
	0x0e72: 'Hsi_ChinElectronics',
	0x0e75: 'TVSElectronics',
	0x0e79: 'Archos',
	0x0e7b: 'On_TechIndustry',
	0x0e7e: 'Gmate',
	0x0e82: 'ChingTaiElectricWireCable',
	0x0e8c: 'WellForceElectronic',
	0x0e90: 'WiebeTech',
	0x0e91: 'VTechEngineeringCanada',
	0x0e92: 'CsGloryEnterprise',
	0x0e93: 'eMTechnics',
	0x0e95: 'Future',
	0x0e96: 'ApluxCommunications',
	0x0e97: 'Fingerworks',
	0x0e98: 'AdvancedAnalogicTechnologies',
	0x0e99: 'ParallelDice',
	0x0e9a: 'TAHSINGIndustries',
	0x0e9b: 'ADTEC',
	0x0e9c: 'Streamzap',
	0x0e9f: 'Tamura',
	0x0ea0: 'Ours',
	0x0ea6: 'NihonComputer',
	0x0ea7: 'MSLEnterprises',
	0x0ea8: 'CenDyne',
	0x0ead: 'Humax2',
	0x0eb1: 'WIS',
	0x0eb2: 'Y_SElectronic',
	0x0eb3: 'Saint',
	0x0eb7: 'EndorAG',
	0x0ebe: 'VWeb',
	0x0ebf: 'Omega',
	0x0ec0: 'LHI',
	0x0ec1: 'AbitComputer',
	0x0ec2: 'SweetrayIndustrial',
	0x0ec3: 'Axell',
	0x0ec4: 'BallracingDevelopments',
	0x0ec5: 'GTInformationSystem',
	0x0ec6: 'InnoVISIONMultimedia',
	0x0ec7: 'ThetaLink',
	0x0ecd: 'LiteOnIT',
	0x0ece: 'TaiSolElectronics',
	0x0ecf: 'PhogenixImaging',
	0x0ed1: 'WinMaxGroup',
	0x0ed2: 'KyotoMicroComputer',
	0x0ed3: 'Wing_TechEnterprise',
	0x0eda: 'NoriakeItron',
	0x0edf: 'e_MDT',
	0x0ee0: 'ShimaSeikiMfg',
	0x0ee1: 'Sarotech',
	0x0ee2: 'AMISemiconductor',
	0x0ee3: 'ComTrue',
	0x0ee4: 'Sunrich',
	0x0eee: 'DigitalStreamTechnology',
	0x0eef: 'D_WAVScientific',
	0x0ef0: 'HitachiCable',
	0x0ef1: 'AichiMicroIntelligent',
	0x0ef2: 'I_OMagic',
	0x0ef3: 'LynnProducts',
	0x0ef4: 'DSIDatotech',
	0x0ef5: 'PointChips',
	0x0ef6: 'Yield',
	0x0ef7: 'SMTech',
	0x0efe: 'WemTechnology',
	0x0efd: 'OasisSemiconductor',
	0x0f06: 'VisualFrontierEnterprise',
	0x0f08: 'CSLWirePlug',
	0x0f0c: 'CAS',
	0x0f0d: 'Hori',
	0x0f0e: 'EnergyFull',
	0x0f12: 'MarsEngineering',
	0x0f13: 'Acetek',
	0x0f19: 'Oracom',
	0x0f1b: 'OnsetComputer',
	0x0f1c: 'FunaiElectric',
	0x0f1d: 'Iwill',
	0x0f21: 'IOI',
	0x0f22: 'SeniorIndustries',
	0x0f23: 'LeaderTech',
	0x0f24: 'FlexP',
	0x0f2d: 'ViPower',
	0x0f2e: 'GenialityMaple',
	0x0f2f: 'Priva',
	0x0f30: 'Jess',
	0x0f31: 'Chrysalis',
	0x0f32: 'YFCBonEagle',
	0x0f37: 'Kokuyo',
	0x0f38: 'Nien_Yi',
	0x0f3d: 'Airprime',
	0x0f41: 'RDC',
	0x0f42: 'Nital',
	0x0f4b: 'StJohn',
	0x0f4c: 'WorldWideCableOpto',
	0x0f4d: 'Microtune',
	0x0f4e: 'Freedom',
	0x0f52: 'WingKey',
	0x0f53: 'DongguanWhiteHorseCableFactory',
	0x0f54: 'KawaiMusicalInstrumentsMfg',
	0x0f55: 'AmbiCom',
	0x0f5c: 'Prairiecomm',
	0x0f5d: 'NewAge',
	0x0f5f: 'Key',
	0x0f60: 'NTK',
	0x0f61: 'Varian',
	0x0f62: 'Acrox',
	0x0f68: 'KobeSteel',
	0x0f69: 'Dionex',
	0x0f6a: 'Vibren',
	0x0f6e: 'IntelligentSystems',
	0x0f73: 'DFI',
	0x0f7c: 'DQ',
	0x0f7d: 'NetBotz',
	0x0f7e: 'Fluke',
	0x0f88: 'VTechHoldings',
	0x0f8b: 'Yazaki',
	0x0f8c: 'YoungGeneration',
	0x0f8d: 'UniwillComputer',
	0x0f8e: 'Kingnet',
	0x0f8f: 'SomaNetworks',
	0x0f97: 'CviLux',
	0x0f98: 'CyberBank',
	0x0f9c: 'HyunWon',
	0x0f9e: 'Lucent',
	0x0fa3: 'StarconnElectronic',
	0x0fa4: 'ATL',
	0x0fa5: 'Sotec',
	0x0fa7: 'EpoxComputer',
	0x0fa8: 'LogicControls',
	0x0faf: 'WinpointElectronic',
	0x0fb0: 'HaurtianWireCable',
	0x0fb1: 'IncloseDesign',
	0x0fb2: 'Juan_ChernIndustrial',
	0x0fb8: 'Wistron',
	0x0fb9: 'AACom',
	0x0fba: 'SanShingElectronics',
	0x0fbb: 'BitwiseSystems',
	0x0fc1: 'MitacInternatinal',
	0x0fc2: 'PlugandJackIndustrial',
	0x0fc5: 'DelcomEngineering',
	0x0fc6: 'DataplusSupplies',
	0x0fca: 'ResearchInMotion',
	0x0fce: 'SonyEricssonMobileCommunicationsAB',
	0x0fcf: 'DynastreamInnovations',
	0x0fd0: 'Tulip',
	0x0fd4: 'Tenovis',
	0x0fd5: 'DirectAccess',
	0x0fdc: 'MicroPlus',
	0x0fe4: 'in_TechElectronics',
	0x0fe5: 'Greenconn',
	0x0fe9: 'DVICO',
	0x0fea: 'UnitedComputer',
	0x0feb: 'CRSElectronic',
	0x0fec: 'UMCElectronics',
	0x0fed: 'Access',
	0x0fee: 'Xsido',
	0x0fef: 'MJResearch',
	0x0ff6: 'CoreValley',
	0x0ff7: 'CHISHINGComputerAccessories',
	0x0fff: 'Aopen',
	0x1000: 'SpeedTech',
	0x1001: 'RitronicsComponents',
	0x1003: 'Sigma',
	0x1004: 'LGElectronics',
	0x1005: 'Apacer',
	0x1006: 'iRiver',
	0x1009: 'Emuzed',
	0x100a: 'AVChaseway',
	0x100b: 'ChouChinIndustrial',
	0x100d: 'Netopia',
	0x1010: 'FukudaDenshi',
	0x1011: 'MobileMediaTech',
	0x1012: 'SDKMFibres',
	0x1013: 'TST',
	0x1014: 'Densitron',
	0x1015: 'SoftronicsPty',
	0x1016: 'XiamenHungsEnterprise',
	0x1017: 'SpeedyIndustrialSupplies',
	0x1019: 'ElitegroupEcs',
	0x1020: 'Labtec',
	0x1022: 'ShinkoShoji',
	0x1025: 'Hyper_Paltek',
	0x1026: 'Newly',
	0x1027: 'TimeDomain',
	0x1028: 'Inovys',
	0x1029: 'AtlanticCoastTelesys',
	0x102a: 'Ramos',
	0x102b: 'Infotronic',
	0x102c: 'EtomsElectronics',
	0x102d: 'Winic',
	0x1031: 'Comax',
	0x1032: 'C_One',
	0x1033: 'Nucam',
	0x1038: 'Ideazon',
	0x1039: 'Devolo',
	0x1043: 'iCreate',
	0x1044: 'ChuYuenEnterprise',
	0x1046: 'WinbondElectronicsHex',
	0x104c: 'AMCOTEC',
	0x1053: 'ImmanuelElectronics',
	0x1054: 'BMS',
	0x1055: 'ComplexMicroInterconnection',
	0x1056: 'HsinChenEnt',
	0x1057: 'ONSemiconductor',
	0x1058: 'WesternDigital',
	0x1059: 'GieseckeDevrient',
	0x105c: 'HongJiElectricWireCable',
	0x105d: 'DelkinDevices',
	0x105e: 'ValenceSemiconductor',
	0x105f: 'ChinShongEnterprise',
	0x1060: 'EasthomeIndustrial',
	0x1063: 'MotorolaElectronicsHex',
	0x1065: 'CCYU',
	0x106a: 'LoyalLegend',
	0x106c: 'CuritelCommunications',
	0x106d: 'SanChiehManufacturing',
	0x106e: 'ConectL',
	0x106f: 'MoneyControls',
	0x1076: 'GCTSemiconductor',
	0x107d: 'ArlecAustralia',
	0x107e: 'MidoriyaElectric',
	0x107f: 'KidzMouse',
	0x1082: 'Shin_Etsukaken',
	0x1083: 'CanonElectronics',
	0x1084: 'Pantech',
	0x108a: 'ChloridePowerProtection',
	0x108b: 'Grand_tek',
	0x108c: 'RobertBosch',
	0x1099: 'SurfaceOptics',
	0x109a: 'DATASOFTSystems',
	0x109f: 'eSOL',
	0x10a0: 'Hirotech',
	0x10a3: 'MitsubishiMaterials',
	0x10a9: 'SKTeletech',
	0x10aa: 'CablesToGo',
	0x10ab: 'USI',
	0x10ac: 'Honeywell',
	0x10ae: 'Princeton',
	0x10b5: 'Comodo',
	0x10b8: 'DiBcom',
	0x10bb: 'TM',
	0x10bc: 'Dinging',
	0x10bd: 'TMTTechnology',
	0x10bf: 'SmartHome',
	0x10c4: 'CygnalIntegratedProducts',
	0x10c5: 'SaneiElectric',
	0x10c6: 'Intec',
	0x10cb: 'Eratech',
	0x10cc: 'GBMConnector',
	0x10cd: 'Kycon',
	0x10cf: 'VellemanComponents',
	0x10d1: 'HottingerBaldwinMeasurement',
	0x10d4: 'ManBoonManufactory',
	0x10d5: 'UniClass',
	0x10d6: 'ActionsSemiconductor',
	0x10de: 'Authenex',
	0x10df: 'in_WinDevelopment',
	0x10e0: 'Post_OpVideo',
	0x10e1: 'CablePlus',
	0x10e2: 'NadaElectronics',
	0x10ec: 'Vast',
	0x10fb: 'Pictos',
	0x10fd: 'AnubisElectronics',
	0x1a0a: 'DotDotDot',
	0x1100: 'VirTouch',
	0x1101: 'EasyPassIndustrial',
	0x1108: 'Brightcom',
	0x1110: 'AnalogDevicesCanada',
	0x1111: 'Pandora',
	0x1112: 'YMELECTRIC',
	0x1113: 'MedionAG',
	0x111e: 'VSOElectric',
	0x112e: 'MasterHillElectricWireandCable',
	0x112f: 'Cellon',
	0x1130: 'Tenx',
	0x1131: 'IntegratedSystemSolution',
	0x1132: 'ToshibaDigitalMediaEquipmentHex',
	0x113c: 'ArinTech',
	0x113d: 'MapowerElectronics',
	0x1141: 'VOneMultimedia',
	0x1142: 'CyberScan',
	0x1147: 'EverGreatElectricWireandCable',
	0x114b: 'Sphairon',
	0x114c: 'TiniusOlsenTestingMachine',
	0x114d: 'AlphaImaging',
	0x1162: 'Secugen',
	0x1163: 'DeLormePublishing',
	0x1164: 'YUANHigh_TechDevelopment',
	0x1165: 'TelsonElectronics',
	0x1166: 'Bantam',
	0x1167: 'SalientSystems',
	0x1168: 'BizConn',
	0x116e: 'Gigastorage',
	0x116f: 'Silicon10',
	0x1175: 'ShengyihSteelMold',
	0x117d: 'SantaElectronic',
	0x117e: 'JNC',
	0x1182: 'Venture',
	0x1183: 'DigitalDream',
	0x1184: 'KyoceraElco',
	0x118f: 'YouYang',
	0x1190: 'Tripace',
	0x1191: 'LoyaltyFounderEnterprise',
	0x1196: 'YankeeRobotics',
	0x1197: 'Technoimagia',
	0x1198: 'StarShine',
	0x1199: 'SierraWireless',
	0x119a: 'ZHANQI',
	0x119b: 'ruwidoaustria',
	0x11a0: 'ChipconAS',
	0x11a3: 'Technovas',
	0x11aa: 'GlobalMediaGroup',
	0x11ab: 'ExitoElectronics',
	0x11db: 'Topfield',
	0x11f5: 'Siemens',
	0x11f7: 'Alcatel',
	0x1209: 'InterBiometrics',
	0x120e: 'HudsonSoft',
	0x121e: 'Jungsoft',
	0x1241: 'BelkinHex',
	0x124a: 'AirVast',
	0x124b: 'Nyko',
	0x1267: 'Logic3_SpectraVideoplc',
	0x126e: 'StrobeData',
	0x126f: 'TwinMOS',
	0x1275: 'XaxeroMarineSoftwareEngineering',
	0x1286: 'MarvellSemiconductor',
	0x1292: 'Innomedia',
	0x1293: 'BelkinComponentsHex',
	0x12d1: 'Huawei',
	0x12ef: 'Tapwave',
	0x12fd: 'AINComm',
	0x1307: 'TranscendInformation',
	0x1310: 'Roper',
	0x1312: 'ICSElectronics',
	0x131d: 'NaturalPoint',
	0x132b: 'KonicaMinolta',
	0x1342: 'Mobility',
	0x134e: 'DigbysBitpileDBADBit',
	0x1370: 'Swissbit',
	0x1385: 'Netgear',
	0x1398: 'Q_tec',
	0x13b0: 'Alesis',
	0x13b1: 'Linksys1',
	0x13d2: 'SharkMultimedia',
	0x13d3: 'ImcNetworks',
	0x13fe: 'KingstonInc',
	0x1453: 'RadioShack',
	0x1462: 'MicroStarInternationalHex',
	0x147a: 'FormosaIndustrialComputing',
	0x1484: 'ElsaHex',
	0x148f: 'Ralink',
	0x14aa: 'AVerMedia',
	0x14b2: 'Atheros',
	0x14c2: 'GemlightComputer',
	0x1518: 'CheshireEngineering',
	0x1520: 'Bitwire',
	0x1524: 'ENEHex',
	0x152d: 'JMicron',
	0x152e: 'LG',
	0x1546: 'U_BloxAG',
	0x1554: 'ProlinkMicrosystems',
	0x1568: 'SunfPu',
	0x15c2: 'SoundGraphInc',
	0x15c6: 'LaboratoiresMXM',
	0x15e1: 'RSA',
	0x15e8: 'SohoWare',
	0x15e9: 'PacificDigital',
	0x15f4: 'HanfTek',
	0x1604: 'Tascam',
	0x1606: 'UmaxHex',
	0x1608: 'InsideOutNetworksHex',
	0x1645: 'EntregaHex',
	0x1657: 'StruckInnovativeSysteme',
	0x1668: 'ActiontecElectronicsHex',
	0x1669: 'PiKRON',
	0x1690: 'AskeyComputerHex',
	0x1696: 'HitachiVideoandInformationSystem',
	0x1697: 'VTecTest',
	0x1706: 'BlueView',
	0x1733: 'CellinkTechnology',
	0x1781: 'MetaGeek',
	0x17b3: 'GreyInnovation',
	0x17eb: 'Cornice',
	0x17ef: 'ChipsBnk',
	0x1822: 'Twinhan',
	0x185b: 'Compro',
	0x187c: 'Alienware',
	0x1894: 'Topseed',
	0x18d9: 'Kaba',
	0x1977: 'T_Logic',
	0x1995: 'Trillium',
	0x1b47: 'Energizer',
	0x1c87: 'n2nTelekomunikace',
	0x1ebb: 'NuCORE',
	0x2001: 'D_LinkHex',
	0x2040: 'Hauppauge',
	0x2101: 'ActionStar',
	0x2162: 'Creative',
	0x2222: 'MacAllyHex',
	0x2233: 'RadioShackCorp',
	0x22b8: 'MotorolaPCS',
	0x22b9: 'eTurboTouch',
	0x22ba: 'TechnologyInnovationHoldings',
	0x2304: 'PinnacleSystemsHex',
	0x2318: 'ShiningTechnologies',
	0x2375: 'DigitAtlway',
	0x2406: 'SANHODigitalElectronics',
	0x2478: 'Tripp_Lite',
	0x2632: 'TwinMOSHex',
	0x2650: 'ElectronicsForImagingHex',
	0x2770: 'NHJ',
	0x2899: 'ToptronicIndustrial',
	0x2fb2: 'FujitsuHex',
	0x3125: 'Eagletron',
	0x3176: 'WhanamElectronics',
	0x3340: 'Yakumo',
	0x3504: 'MicroStar',
	0x3538: 'PowerQuotientHex',
	0x3579: 'DIVA',
	0x3636: 'InVibro',
	0x3838: 'WEM',
	0x3923: 'NationalInstruments',
	0x4102: 'iRiverHex',
	0x413c: 'DellComputerHex',
	0x4242: 'USBDesignbyExample',
	0x4146: 'USBest',
	0x4572: 'ShuttleHex',
	0x4586: 'Panram',
	0x4670: 'EMSProduction',
	0x5032: 'Grandtec',
	0x5041: 'Linksys2',
	0x544d: 'Transmeta',
	0x5543: 'UC_Logic',
	0x55aa: 'OnSpec',
	0x636c: 'CoreLogic',
	0x6666: 'PrototypeproductVendorID',
	0x6993: 'Freshtel',
	0x6a75: 'JujoShanghai',
	0x8086: 'Intel',
	0x8341: 'EGOSystems',
	0x9710: 'MosChip',
	0xc251: 'KeilInc',
	0xeb1a: 'eMPIA',
};

////////////////////////////////////////////////////////
// LOGITECH_PRODUCT_CONNECTION_TYPE

my.LOGITECH_PRODUCT_CONNECTION_TYPE = {
	Other : 0,

	CordedDevice   : 1,
	WirelessDevice : 2,
	Transceiver    : 3,

	toString : function(value) {
		return this.getOwnPropertyNameForValue(value)
			.replace(/_/g, " ").capitalize();
	},
	fromCategory : function(category) {
		switch(category) {
			case my.LOGITECH_PRODUCT_CATEGORY.VirtualUsbGameController:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbScanner:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbCamera:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbAudio:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbHub:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbSpecial:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbMouse:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbRemoteControl:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbPcGamingDevice:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbKeyboard:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbTrackBall:
			case my.LOGITECH_PRODUCT_CATEGORY.Usb3dControlDevice:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbOtherPointingDevice:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbConsoleGamingDevice:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbToolsCorded: 
				return my.LOGITECH_PRODUCT_CATEGORY.CordedDevice;

			case my.LOGITECH_PRODUCT_CATEGORY.UsbBluetoothReceiver:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbReceiver:
			case my.LOGITECH_PRODUCT_CATEGORY.QuadMouseTransceiver:
			case my.LOGITECH_PRODUCT_CATEGORY.QuadDesktopTransceiver:
			case my.LOGITECH_PRODUCT_CATEGORY.UsbToolsTransceiver:
				return my.LOGITECH_PRODUCT_CATEGORY.Transceiver;

			case my.LOGITECH_PRODUCT_CATEGORY.BluetoothMouse:
			case my.LOGITECH_PRODUCT_CATEGORY.BluetoothKeyboard:
			case my.LOGITECH_PRODUCT_CATEGORY.BluetoothRemoteControl:
			case my.LOGITECH_PRODUCT_CATEGORY.BluetoothReserved:
			case my.LOGITECH_PRODUCT_CATEGORY.BluetoothAudio:
			case my.LOGITECH_PRODUCT_CATEGORY.QuadFapDevice:
			case my.LOGITECH_PRODUCT_CATEGORY.QuadMouse:
			case my.LOGITECH_PRODUCT_CATEGORY.QuadKeyboard: 
				return my.LOGITECH_PRODUCT_CATEGORY.WirelessDevice;

			default:
				return my.LOGITECH_PRODUCT_CATEGORY.Other;
		}
	}
};

////////////////////////////////////////////////////////
// LOGITECH_PRODUCT_CATEGORY

// TODO: add BLE products
my.LOGITECH_PRODUCT_CATEGORY = {
	Other : 0,

	VirtualUsbGameController : 1,
	UsbScanner               : 2,
	UsbCamera                : 3,
	UsbAudio                 : 4,
	UsbHub                   : 5,
	UsbSpecial               : 6,

	BluetoothMouse           : 7,
	BluetoothKeyboard        : 8,
	BluetoothNumpad          : 9,
	BluetoothRemoteControl   : 10,
	BluetoothReserved        : 11,
	BluetoothAudio           : 12,

	UsbBluetoothReceiver     : 13,
	UsbReceiver              : 14,

	UsbMouse                 : 15,
	UsbRemoteControl         : 16,
	UsbPcGamingDevice        : 17,
	UsbKeyboard              : 18,
	UsbTrackBall             : 19,
	Usb3dControlDevice       : 20,
	UsbOtherPointingDevice   : 21,
	UsbConsoleGamingDevice   : 22,
	UsbToolsOther            : 23,
	UsbToolsCorded           : 24,
	UsbToolsTransceiver      : 25,

	QuadMouse                : 26,
	QuadKeyboard             : 27,
	QuadGamingDevice         : 28,
	QuadFapDevice            : 29,
	QuadMouseTransceiver     : 30,
	QuadDesktopTransceiver   : 31,
	QuadGamingTransceiver    : 32,

	toString : function(value) {
		return this.getOwnPropertyNameForValue(value)
			.replace(/_/g, " ").capitalize();
	},
	fromPid : function(pid) {
		var inRange = function(id, min, max) {
			return min <= id && id <= max; 
		}

		if (inRange(pid, 0x0000, 0x00FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.VirtualUsbGameController;
		}
		if (inRange(pid, 0x0400, 0x040F)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbScanner;
		}
		if (inRange(pid, 0x0800, 0x08FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbCamera;
		}
		if (inRange(pid, 0x0900, 0x09FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbCamera;
		}
		if (inRange(pid, 0xD000, 0xD00F)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbCamera;
		}
		if (inRange(pid, 0x8900, 0x89FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbCamera;
		}
		if (inRange(pid, 0x9900, 0x99FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbCamera;
		}
		if (inRange(pid, 0x0A00, 0x0AFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbAudio;
		}
		if (inRange(pid, 0x0B00, 0x0BFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbHub;
		}

		if (inRange(pid, 0x5000, 0x5FFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbToolsTransceiver;
		}

		if (inRange(pid, 0xA000, 0xAFFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbSpecial;
		}

		if (inRange(pid, 0xB000, 0xB0FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.BluetoothMouse;
		}
		if (inRange(pid, 0xB300, 0xB3DF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.BluetoothKeyboard;
		}
		if (inRange(pid, 0xB3E0, 0xB4FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.BluetoothNumpad;
		}
		if (inRange(pid, 0xB400, 0xB4FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.BluetoothRemoteControl;
		}
		if (inRange(pid, 0xB500, 0xB5FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.BluetoothReserved;
		}
		if (inRange(pid, 0xBA00, 0xBAFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.BluetoothAudio;
		}

		if (inRange(pid, 0xC700, 0xC7FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbBluetoothReceiver;
		}

		if (inRange(pid, 0xC000, 0xC0FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbMouse;
		}
		if (inRange(pid, 0xC100, 0xC1FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbRemoteControl;
		}
		if (inRange(pid, 0xC200, 0xC2FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbPcGamingDevice;
		}
		if (inRange(pid, 0xC300, 0xC3FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbKeyboard;
		}
		if (inRange(pid, 0xC400, 0xC4FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbTrackBall;
		}
		if (inRange(pid, 0xC500, 0xC5FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbReceiver;
		}
		if (inRange(pid, 0xC600, 0xC6FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.Usb3dControlDevice;
		}
		if (inRange(pid, 0xC800, 0xC8FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbOtherPointingDevice;
		}
		if (inRange(pid, 0xCA00, 0xCCFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbConsoleGamingDevice;
		}

		if (pid == 0xF010) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbToolsCorded;
		}
		if (inRange(pid, 0xF000, 0xFFFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.UsbToolsTransceiver;
		}

		if (inRange(pid, 0x1000, 0x1FFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.QuadMouse;
		}
		if (inRange(pid, 0x2000, 0x2FFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.QuadKeyboard;
		}
		if (inRange(pid, 0x3000, 0x3FFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.QuadGamingDevice;
		}
		if (inRange(pid, 0x4000, 0x4FFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.QuadFapDevice;
		}
		if (inRange(pid, 0x8000, 0x87FF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.QuadMouseTransceiver;
		}
		if (inRange(pid, 0x8800, 0x8FFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.QuadDesktopTransceiver;
		}
		if (inRange(pid, 0x9000, 0x9FFF)) {
			return my.LOGITECH_PRODUCT_CATEGORY.QuadGamingTransceiver;
		}

		return my.LOGITECH_PRODUCT_CATEGORY.Other;
	}
};

return my;

}(devices || {}));
